import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { menuTranslations } from '../translations/menuTranslations';

export type Language = 'de' | 'en' | 'vi' | 'es';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, params?: Record<string, string>) => string;
  getCategoryTitle: (categoryName: string) => string;
  getCategorySubtitle: (categoryName: string) => string;
  getDishDescription: (dishName: string) => string;
  getTagTranslation: (tag: string) => string;
  getWeekdayNames: () => string[];
  getShortWeekdayNames: () => string[];
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = '@moggi_app_language';

// Übersetzungen
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Profile Edit Screen
    'profile.edit': 'Profil bearbeiten',
    'profile.personalData': 'Persönliche Daten',
    'profile.updateInfo': 'Aktualisiere deine Kontoinformationen',
    'profile.firstName': 'Vorname',
    'profile.firstNamePlaceholder': 'Dein Vorname',
    'profile.lastName': 'Nachname',
    'profile.lastNamePlaceholder': 'Dein Nachname',
    'profile.email': 'E-Mail-Adresse',
    'profile.emailPlaceholder': 'deine@email.com',
    'profile.language': 'Sprache',
    'profile.languageSubtitle': 'Wähle deine bevorzugte Sprache',
    'profile.save': 'Änderungen speichern',
    'profile.saveSuccess': 'Profil erfolgreich aktualisiert!',
    'profile.emailInfo': 'Deine E-Mail-Adresse wird für die Bestätigung von Bestellungen und Reservierungen verwendet.',
    'profile.fillAllFields': 'Bitte fülle alle Felder aus',
    'profile.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'profile.error': 'Fehler',
    'profile.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten',
    // Language Options
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.vietnamese': 'Tiếng Việt',
    'language.spanish': 'Spanisch',
    // Account Screen
    'account.title': 'Konto',
    'account.subtitle': 'Verwalte dein Profil',
    'account.guest': 'Gast',
    'account.notLoggedIn': 'Noch nicht angemeldet',
    'account.loginNow': 'Jetzt anmelden',
    'account.loginSuccess': 'Erfolgreich angemeldet!',
    'account.language': 'Sprache',
    'account.languageSubtitle': 'Wähle deine bevorzugte Sprache',
    'account.orders': 'Meine Bestellungen',
    'account.ordersSubtitle': 'Bestellhistorie ansehen',
    'account.editProfile': 'Profil bearbeiten',
    'account.editProfileSubtitle': 'Name, E-Mail, etc.',
    'account.logout': 'Abmelden',
    'account.logoutConfirm': 'Möchtest du dich wirklich abmelden?',
    'account.cancel': 'Abbrechen',
    'account.comingSoon': 'Diese Funktion wird bald verfügbar sein',
    // Home Screen
    'home.heroTitle': 'Zwei Welten, eine Vision - Asiatische Küche neu interpretiert',
    'home.heroSubtitle': 'Willkommen in einer Welt, wo Tradition auf Innovation trifft',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan verbindet die authentischen Aromen seiner südchinesischen Heimat mit moderner Kreativität. Geprägt von den lebendigen Märkten Guangzhous, bringt er jahrtausendealte Esskultur auf kleine Teller.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey bringt die hohe Kunst des Sushi-Handwerks nach Nürnberg. Mit über 15 Jahren Erfahrung in der Edomae-Tradition erschafft er jedes Stück mit Respekt für das Produkt und japanischer Perfektion.',
    'home.reserveTable': 'Tisch reservieren',
    // Products Screen
    'products.title': 'Speisekarte',
    'products.subtitle': 'Entdecke unsere Köstlichkeiten',
    'products.highlights': 'Highlights',
    'products.smallDishes': 'Kleine Gerichte',
    'products.fusionSpecials': 'Fusion Specials',
    'products.sushi': 'Sushi',
    'products.sides': 'Beilagen & More',
    // Cart Screen
    'cart.title': 'Warenkorb',
    'cart.subtitle': 'Deine ausgewählten Artikel',
    'cart.items': 'Artikel',
    'cart.empty': 'Dein Warenkorb ist leer',
    'cart.emptySubtext': 'Füge Produkte hinzu, um loszulegen',
    'cart.clear': 'Warenkorb leeren',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    // More Screen
    'more.title': 'Mehr',
    'more.subtitle': 'Weitere Optionen',
    'more.contact': 'Kontakt',
    'more.contactSubtitle': 'Telefon, E-Mail & Adresse',
    'more.privacy': 'Datenschutz',
    'more.privacySubtitle': 'Datenschutzerklärung',
    'more.imprint': 'Impressum',
    'more.imprintSubtitle': 'Rechtliche Informationen',
    'more.appName': 'MOGGI App',
    'more.appSubtitle': 'Restaurant-App',
    'more.appVersion': 'Version 1.0.0',
    'more.comingSoon': 'Diese Funktion wird bald verfügbar sein',
    'more.info': 'Info',
    // Navigation Tabs
    'nav.home': 'Home',
    'nav.menu': 'Speisekarte',
    'nav.cart': 'Warenkorb',
    'nav.account': 'Konto',
    'nav.more': 'Mehr',
    // Contact Screen
    'contact.title': 'Kontakt',
    'contact.phone': 'Telefon',
    'contact.location': 'Standort',
    'contact.email': 'E-Mail',
    'contact.openingHours': 'Öffnungszeiten',
    'contact.copied': 'Kopiert',
    'contact.copiedMessage': '{label} wurde in die Zwischenablage kopiert',
    'contact.copyError': 'Fehler',
    'contact.monday': 'Montag:',
    'contact.tuesdayWednesday': 'Dienstag - Mittwoch:',
    'contact.thursdaySaturday': 'Donnerstag-Samstag:',
    'contact.sunday': 'Sonntag:',
    'contact.closedDay': 'Ruhetag (geschlossen)',
    'contact.lunchService': 'Mittagsservice',
    'contact.eveningService': 'Abendservice',
    // Product Categories
    'category.newIn': 'New In',
    'category.businessLunch': 'Business Lunch',
    'category.tapasMeat': 'Tapas Fleisch',
    'category.tapasFish': 'Tapas Fisch',
    'category.tapasVegetarian': 'Tapas vegetarisch',
    'category.sticks': 'Sticks',
    'category.crisps': 'Crisps',
    'category.baos': 'Baos',
    'category.noriTacos': 'Nori Tacos',
    'category.sashimi': 'Sashimi',
    'category.nigiri': 'Nigiri',
    'category.hosomaki': 'Hosomaki',
    'category.uramaki': 'Uramaki',
    'category.specialRoll': 'Special Roll',
    'category.crispyRolls': 'Crispy Rolls',
    'category.sides': 'Beilagen',
    'contact.copyErrorMessage': 'Konnte nicht kopiert werden',
    // Login Screen
    'login.title': 'Login',
    'login.sectionTitle': 'Anmeldung',
    'login.emailLabel': 'E-Mail / Benutzername',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Passwort',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Passwort vergessen?',
    'login.button': 'Anmelden',
    'login.fillAllFields': 'Bitte fülle alle Felder aus',
    'login.invalidCredentials': 'E-Mail oder Passwort ist falsch',
    'login.emailNotConfirmed': 'Bitte bestätige deine E-Mail-Adresse',
    'login.error': 'Ein Fehler ist aufgetreten',
    'login.noAccount': 'Noch kein Account?',
    'login.registerNow': 'Erstelle jetzt kostenlos einen Account',
    'login.accountInfo': 'Mit einem Account kannst du deine Bestellhistorie einsehen und Treuepunkte sammeln.',
    // Register Screen
    'register.title': 'Registrieren',
    'register.pageTitle': 'Konto erstellen',
    'register.subtitle': 'Registrierung für exklusive Vorteile',
    'register.firstName': 'Vorname',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Nachname',
    'register.lastNamePlaceholder': 'Mustermann',
    'register.email': 'E-Mail',
    'register.emailPlaceholder': 'deine@email.com',
    'register.birthDate': 'Geburtsdatum',
    'register.dayPlaceholder': 'TT',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'JJJJ',
    'register.password': 'Passwort',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Konto erstellen',
    'register.fillAllFields': 'Bitte fülle alle Felder aus',
    'register.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein',
    'register.invalidBirthDate': 'Bitte gib ein vollständiges Geburtsdatum ein',
    'register.emailAlreadyRegistered': 'Diese E-Mail ist bereits registriert. Bitte melde dich an.',
    'register.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'register.weakPassword': 'Passwort ist zu schwach. Verwende mindestens 6 Zeichen.',
    'register.error': 'Ein Fehler ist aufgetreten',
    'register.successTitle': 'Registrierung erfolgreich!',
    'register.successMessage': 'Dein Konto wurde erstellt.{newline}Du wirst zur Anmeldung weitergeleitet...',
    'register.terms': 'Mit der Registrierung akzeptierst du unsere',
    'register.termsOfService': 'Nutzungsbedingungen',
    'register.and': 'und',
    'register.privacyPolicy': 'Datenschutzrichtlinien',
    // Checkout Screen
    'checkout.title': 'Checkout',
    'checkout.guestData': 'Gast-Daten',
    'checkout.firstName': 'Vorname',
    'checkout.lastName': 'Nachname',
    'checkout.email': 'E-Mail-Adresse',
    'checkout.notes': 'Hinweise (optional)',
    'checkout.pickupDate': 'Abholdatum',
    'checkout.pickupTime': 'Abholzeit',
    'checkout.selectTime': 'Uhrzeit auswählen',
    'checkout.selectTimePlaceholder': 'Uhrzeit wählen',
    'checkout.selectDate': 'Datum auswählen',
    'checkout.continuePayment': 'Weiter zur Zahlung',
    'checkout.fillAllFields': 'Bitte fülle alle Felder aus',
    'checkout.selectDateFirst': 'Bitte wähle erst ein Datum aus',
    'checkout.selectTimeFirst': 'Bitte wähle eine Uhrzeit aus',
    'checkout.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'checkout.timeUnit': 'Uhr',
    'checkout.pickupInfo': 'Deine Bestellung wird frisch zubereitet. Bitte sei pünktlich zur Abholzeit bei uns in der Katharinengasse 14, Nürnberg.',
    // Order Success Screen
    'orderSuccess.paymentSuccess': 'Zahlung erfolgreich!',
    'orderSuccess.thankYou': 'Vielen Dank, {name}!',
    'orderSuccess.orderNumber': 'Bestellnummer',
    'orderSuccess.confirmationSent': 'Eine Bestätigung wurde an {email} gesendet',
    'orderSuccess.pickup': 'Abholung',
    'orderSuccess.pickupDate': 'Abholdatum',
    'orderSuccess.pickupTime': 'Uhrzeit',
    'orderSuccess.pickupAddress': 'Abholadresse',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Nürnberg',
    'orderSuccess.newOrder': 'Weitere Bestellung',
    'orderSuccess.prepareToday': 'Wir bereiten deine Bestellung frisch zu. Bis gleich!',
    'orderSuccess.prepareTomorrow': 'Deine Bestellung wird morgen frisch zubereitet.',
    'orderSuccess.prepareLater': 'Deine Bestellung wird am Abholtag frisch zubereitet.',
    // Payment Screen
    'payment.title': 'Zahlung',
    'payment.orderSummary': 'Bestellübersicht',
    'payment.pickupDate': 'Abholung',
    'payment.amount': 'Gesamtbetrag',
    'payment.pay': 'Jetzt bezahlen',
    'payment.error': 'Fehler',
    'payment.processing': 'Wird verarbeitet...',
    'payment.selectMethod': 'Wähle deine Zahlungsmethode',
    'payment.items': 'Artikel',
    'payment.time': 'Uhrzeit',
    'payment.name': 'Name',
    'payment.securePayment': 'Sichere Zahlung',
    'payment.creditCard': 'Kreditkarte via Stripe',
    'payment.sslEncrypted': 'SSL-verschlüsselt',
    'payment.pciCompliant': 'PCI-konform',
    'payment.allCards': 'Alle Kreditkarten',
    'payment.stripeInfo': 'Du wirst zum sicheren Stripe-Zahlungsformular weitergeleitet. Deine Kartendaten werden verschlüsselt übertragen.',
    'payment.toPay': 'Zu zahlen',
    'payment.processingPayment': 'Verarbeite Zahlung...',
    // Reservation Screen
    'reservation.title': 'Tisch reservieren',
    'reservation.step1': 'Schritt 1: Datum & Uhrzeit',
    'reservation.step2': 'Schritt 2: Details',
    'reservation.selectDate': 'Datum auswählen',
    'reservation.selectTime': 'Uhrzeit auswählen',
    'reservation.time': 'Uhrzeit',
    'reservation.guests': 'Anzahl Gäste',
    'reservation.fullName': 'Vollständiger Name',
    'reservation.phone': 'Telefonnummer',
    'reservation.email': 'E-Mail',
    'reservation.notes': 'Anmerkungen (optional)',
    'reservation.confirm': 'Reservierung bestätigen',
    'reservation.confirmed': 'Reservierung erfolgreich!',
    'reservation.confirmMessage': 'Deine Reservierung wurde bestätigt. Wir freuen uns auf deinen Besuch!',
    // Order History Screen
    'orderHistory.title': 'Meine Bestellungen',
    'orderHistory.subtitle': 'Bestellhistorie',
    'orderHistory.empty': 'Noch keine Bestellungen',
    'orderHistory.emptySubtext': 'Deine Bestellungen werden hier angezeigt',
    // Dish Detail
    'dish.quantity': 'Menge',
    'dish.addToCart': 'In den Warenkorb',
    // Verify Email Screen
    'verify.title': 'E-Mail bestätigen',
    'verify.enterCode': 'Code eingeben',
    'verify.codeSentTo': 'Wir haben einen 6-stelligen Code an',
    'verify.sent': 'gesendet.',
    'verify.warning': 'Wichtig: Schließe diesen Screen nicht! Bei Verlassen musst du dich neu registrieren.',
    'verify.confirm': 'Bestätigen',
    'verify.resendCode': 'Code erneut senden',
    'verify.enterCodeError': 'Bitte gib den 6-stelligen Code ein',
    'verify.invalidCode': 'Ungültiger Code',
    'verify.emailConfirmed': 'E-Mail bestätigt! Melde dich an...',
    'verify.loginFailed': 'Anmeldung fehlgeschlagen. Bitte melde dich manuell an.',
    'verify.newCodeSent': 'Neuer Code wurde gesendet!',
    'verify.codeNotSent': 'Code konnte nicht erneut gesendet werden',
    'verify.cancelTitle': 'Registrierung abbrechen?',
    'verify.cancelMessage': 'Wenn du jetzt abbrichst, musst du dich neu registrieren. Der unbestätigte Account wird gelöscht.',
    'verify.stayHere': 'Hier bleiben',
    'verify.cancelButton': 'Abbrechen',
    // Forgot Password Screen
    'forgotPassword.title': 'Passwort zurücksetzen',
    'forgotPassword.heading': 'Passwort vergessen?',
    'forgotPassword.subtitle': 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.',
    'forgotPassword.email': 'E-Mail',
    'forgotPassword.emailPlaceholder': 'deine@email.com',
    'forgotPassword.sendLink': 'Link senden',
    'forgotPassword.backToLogin': 'Zurück zur Anmeldung',
    'forgotPassword.enterEmail': 'Bitte gib deine E-Mail-Adresse ein',
    'forgotPassword.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'forgotPassword.emailSent': 'E-Mail versendet! Prüfe deinen Posteingang und klicke auf den Link.',
    'forgotPassword.error': 'Ein Fehler ist aufgetreten. Bitte versuche es später erneut.',
    // Reset Password Screen
    'resetPassword.title': 'Neues Passwort',
    'resetPassword.heading': 'Passwort zurücksetzen',
    'resetPassword.subtitle': 'Gib dein neues Passwort ein',
    'resetPassword.newPassword': 'Neues Passwort',
    'resetPassword.newPasswordPlaceholder': 'Mindestens 6 Zeichen',
    'resetPassword.confirmPassword': 'Passwort bestätigen',
    'resetPassword.confirmPasswordPlaceholder': 'Passwort wiederholen',
    'resetPassword.changePassword': 'Passwort ändern',
    'resetPassword.fillAllFields': 'Bitte fülle alle Felder aus',
    'resetPassword.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein',
    'resetPassword.passwordMismatch': 'Passwörter stimmen nicht überein',
    'resetPassword.success': 'Passwort wurde erfolgreich geändert!',
    'resetPassword.error': 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
    // Login Checkout Screen
    'loginCheckout.title': 'Login',
    'loginCheckout.subtitle': 'Melde dich an',
    'loginCheckout.sectionTitle': 'Anmeldung',
    'loginCheckout.email': 'E-Mail / Benutzername',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Passwort',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Einloggen & Fortfahren',
    'loginCheckout.noAccount': 'Noch kein Account?',
    'loginCheckout.createAccount': 'Erstelle jetzt kostenlos einen Account',
    'loginCheckout.accountInfo': 'Mit einem Account kannst du deine Bestellhistorie einsehen und Treuepunkte sammeln.',
    'loginCheckout.fillAllFields': 'Bitte fülle alle Felder aus',
    'loginCheckout.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'loginCheckout.invalidCredentials': 'E-Mail oder Passwort falsch',
    'loginCheckout.total': 'Gesamt',
    // Order History Screen - erweitern
    'orderHistory.noOrders': 'Noch keine Bestellungen',
    'orderHistory.orderCount': '{count} Bestellung',
    'orderHistory.ordersCount': '{count} Bestellungen',
    'orderHistory.emptyTitle': 'Keine Bestellungen',
    'orderHistory.emptyDescription': 'Du hast noch keine Bestellungen aufgegeben',
    'orderHistory.orderNumber': 'Bestellung #{number}',
    'orderHistory.pickup': 'Abholung',
    'orderHistory.items': 'Artikel',
    'orderHistory.total': 'Gesamt',
    'orderHistory.statusPending': 'Ausstehend',
    'orderHistory.statusConfirmed': 'Bestätigt',
    'orderHistory.statusReady': 'Bereit',
    'orderHistory.statusCompleted': 'Abgeschlossen',
    'orderHistory.statusCancelled': 'Storniert',
    'orderHistory.loadError': 'Fehler beim Laden der Bestellungen',
    // Help & Support Screen
    'helpSupport.title': 'Hilfe & Support',
    'helpSupport.welcomeTitle': 'Wie können wir helfen?',
    'helpSupport.welcomeSubtitle': 'Hier findest du Antworten auf häufige Fragen und unsere Kontaktdaten',
    'helpSupport.faqTitle': 'Häufige Fragen',
    'helpSupport.contactTitle': 'Kontakt',
    'helpSupport.supportAvailable': 'Support verfügbar',
    'helpSupport.supportHours': 'Mo-Fr: 9:00 - 18:00 Uhr{newline}Sa-So: 10:00 - 16:00 Uhr',
    'helpSupport.urgentTitle': 'Dringende Probleme?',
    'helpSupport.urgentSubtitle': 'Bei dringenden Problemen mit deiner Bestellung rufe uns direkt an',
    'helpSupport.callNow': 'Jetzt anrufen',
    'helpSupport.faq1Question': 'Wie kann ich eine Bestellung aufgeben?',
    'helpSupport.faq1Answer': 'Wähle deine gewünschten Gerichte aus der Speisekarte aus, füge sie zum Warenkorb hinzu und gehe zur Kasse. Du kannst zwischen Abholung und Lieferung wählen.',
    'helpSupport.faq2Question': 'Welche Zahlungsmethoden werden akzeptiert?',
    'helpSupport.faq2Answer': 'Wir akzeptieren Kreditkarten, Debitkarten und Apple Pay. Alle Zahlungen werden sicher über Stripe verarbeitet.',
    'helpSupport.faq3Question': 'Wie kann ich eine Reservierung machen?',
    'helpSupport.faq3Answer': 'Gehe zum Home-Tab und wähle "Reservierung". Fülle das Formular aus und wir bestätigen deine Reservierung per E-Mail.',
    'helpSupport.faq4Question': 'Kann ich meine Bestellung stornieren?',
    'helpSupport.faq4Answer': 'Bestellungen können bis zu 15 Minuten nach der Aufgabe storniert werden. Kontaktiere uns direkt über die App oder telefonisch unter 0911 63290791.',
    'helpSupport.faq5Question': 'Wie lange dauert die Lieferung?',
    'helpSupport.faq5Answer': 'Die Lieferzeit beträgt normalerweise 30-45 Minuten, abhängig von der Entfernung und der aktuellen Auslastung.',
    'helpSupport.faq6Question': 'Was ist die Mindestbestellmenge?',
    'helpSupport.faq6Answer': 'Die Mindestbestellmenge beträgt 15€ für Lieferungen und 10€ für Abholungen.',
    'helpSupport.phone': 'Telefon',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'E-Mail',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Adresse',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlin',
    'helpSupport.hours': 'Öffnungszeiten',
    'helpSupport.hoursValue': 'Mo-So: 11:00 - 23:00 Uhr',
    // Imprint & Privacy Screens
    'imprint.title': 'Impressum',
    'privacy.title': 'Datenschutz',
    // Reservation Success Screen
    'reservationSuccess.title': 'Reservierung bestätigt!',
    'reservationSuccess.thankYou': 'Vielen Dank, {name}!',
    'reservationSuccess.reservationNumber': 'Reservierungsnummer',
    'reservationSuccess.confirmationSent': 'Eine Bestätigung wurde an {email} gesendet',
    'reservationSuccess.details': 'Reservierungsdetails',
    'reservationSuccess.date': 'Datum',
    'reservationSuccess.time': 'Uhrzeit',
    'reservationSuccess.guests': 'Anzahl Personen',
    'reservationSuccess.person': 'Person',
    'reservationSuccess.persons': 'Personen',
    'reservationSuccess.restaurant': 'Restaurant',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Nürnberg',
    'reservationSuccess.backToHome': 'Zurück zur Startseite',
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolgreich',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.required': 'Pflichtfeld',
    // Weekdays
    'weekday.sunday': 'Sonntag',
    'weekday.monday': 'Montag',
    'weekday.tuesday': 'Dienstag',
    'weekday.wednesday': 'Mittwoch',
    'weekday.thursday': 'Donnerstag',
    'weekday.friday': 'Freitag',
    'weekday.saturday': 'Samstag',
    // Weekdays Short
    'weekday.short.sunday': 'So',
    'weekday.short.monday': 'Mo',
    'weekday.short.tuesday': 'Di',
    'weekday.short.wednesday': 'Mi',
    'weekday.short.thursday': 'Do',
    'weekday.short.friday': 'Fr',
    'weekday.short.saturday': 'Sa',
    // Date Labels
    'date.today': 'Heute',
    'date.tomorrow': 'Morgen',
  },
  en: {
    // Profile Edit Screen
    'profile.edit': 'Edit Profile',
    'profile.personalData': 'Personal Data',
    'profile.updateInfo': 'Update your account information',
    'profile.firstName': 'First Name',
    'profile.firstNamePlaceholder': 'Your first name',
    'profile.lastName': 'Last Name',
    'profile.lastNamePlaceholder': 'Your last name',
    'profile.email': 'Email Address',
    'profile.emailPlaceholder': 'your@email.com',
    'profile.language': 'Language',
    'profile.languageSubtitle': 'Choose your preferred language',
    'profile.save': 'Save Changes',
    'profile.saveSuccess': 'Profile updated successfully!',
    'profile.emailInfo': 'Your email address is used for order and reservation confirmations.',
    'profile.fillAllFields': 'Please fill in all fields',
    'profile.invalidEmail': 'Please enter a valid email address',
    'profile.error': 'Error',
    'profile.unexpectedError': 'An unexpected error occurred',
    // Language Options
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.vietnamese': 'Tiếng Việt',
    'language.spanish': 'Spanish',
    // Account Screen
    'account.title': 'Account',
    'account.subtitle': 'Manage your profile',
    'account.guest': 'Guest',
    'account.notLoggedIn': 'Not logged in',
    'account.loginNow': 'Login now',
    'account.loginSuccess': 'Successfully logged in!',
    'account.language': 'Language',
    'account.languageSubtitle': 'Choose your preferred language',
    'account.orders': 'My Orders',
    'account.ordersSubtitle': 'View order history',
    'account.editProfile': 'Edit Profile',
    'account.editProfileSubtitle': 'Name, Email, etc.',
    'account.logout': 'Logout',
    'account.logoutConfirm': 'Do you really want to logout?',
    'account.cancel': 'Cancel',
    'account.comingSoon': 'This feature will be available soon',
    // Home Screen
    'home.heroTitle': 'Two Worlds, One Vision - Asian Cuisine Reinterpreted',
    'home.heroSubtitle': 'Welcome to a world where tradition meets innovation',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan combines the authentic flavors of his South Chinese homeland with modern creativity. Shaped by the vibrant markets of Guangzhou, he brings millennia-old culinary culture to small plates.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey brings the high art of sushi craftsmanship to Nuremberg. With over 15 years of experience in the Edomae tradition, he creates each piece with respect for the product and Japanese perfection.',
    'home.reserveTable': 'Reserve Table',
    // Products Screen
    'products.title': 'Menu',
    'products.subtitle': 'Discover our delicacies',
    'products.highlights': 'Highlights',
    'products.smallDishes': 'Small Dishes',
    'products.fusionSpecials': 'Fusion Specials',
    'products.sushi': 'Sushi',
    'products.sides': 'Sides & More',
    // Cart Screen
    'cart.title': 'Cart',
    'cart.subtitle': 'Your selected items',
    'cart.items': 'items',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtext': 'Add products to get started',
    'cart.clear': 'Clear Cart',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    // More Screen
    'more.title': 'More',
    'more.subtitle': 'Additional Options',
    'more.contact': 'Contact',
    'more.contactSubtitle': 'Phone, Email & Address',
    'more.privacy': 'Privacy',
    'more.privacySubtitle': 'Privacy Policy',
    'more.imprint': 'Imprint',
    'more.imprintSubtitle': 'Legal Information',
    'more.appName': 'MOGGI App',
    'more.appSubtitle': 'Restaurant App',
    'more.appVersion': 'Version 1.0.0',
    'more.comingSoon': 'This feature will be available soon',
    'more.info': 'Info',
    // Navigation Tabs
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.more': 'More',
    // Contact Screen
    'contact.title': 'Contact',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.email': 'Email',
    'contact.openingHours': 'Opening Hours',
    'contact.copied': 'Copied',
    'contact.copiedMessage': '{label} has been copied to clipboard',
    'contact.copyError': 'Error',
    'contact.monday': 'Monday:',
    'contact.tuesdayWednesday': 'Tuesday - Wednesday:',
    'contact.thursdaySaturday': 'Thursday - Saturday:',
    'contact.sunday': 'Sunday:',
    'contact.closedDay': 'Closed',
    'contact.lunchService': 'Lunch Service',
    'contact.eveningService': 'Evening Service',
    // Product Categories
    'category.newIn': 'New In',
    'category.businessLunch': 'Business Lunch',
    'category.tapasMeat': 'Tapas Meat',
    'category.tapasFish': 'Tapas Fish',
    'category.tapasVegetarian': 'Tapas Vegetarian',
    'category.sticks': 'Sticks',
    'category.crisps': 'Crisps',
    'category.baos': 'Baos',
    'category.noriTacos': 'Nori Tacos',
    'category.sashimi': 'Sashimi',
    'category.nigiri': 'Nigiri',
    'category.hosomaki': 'Hosomaki',
    'category.uramaki': 'Uramaki',
    'category.specialRoll': 'Special Roll',
    'category.crispyRolls': 'Crispy Rolls',
    'category.sides': 'Sides',
    'contact.copyErrorMessage': 'Could not copy',
    // Login Screen
    'login.title': 'Login',
    'login.sectionTitle': 'Sign In',
    'login.emailLabel': 'Email / Username',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Forgot Password?',
    'login.button': 'Sign In',
    'login.fillAllFields': 'Please fill in all fields',
    'login.invalidCredentials': 'Email or password is incorrect',
    'login.emailNotConfirmed': 'Please confirm your email address',
    'login.error': 'An error occurred',
    'login.noAccount': 'No account yet?',
    'login.registerNow': 'Create a free account now',
    'login.accountInfo': 'With an account, you can view your order history and collect loyalty points.',
    // Register Screen
    'register.title': 'Register',
    'register.pageTitle': 'Create Account',
    'register.subtitle': 'Register for exclusive benefits',
    'register.firstName': 'First Name',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Last Name',
    'register.lastNamePlaceholder': 'Smith',
    'register.email': 'Email',
    'register.emailPlaceholder': 'your@email.com',
    'register.birthDate': 'Date of Birth',
    'register.dayPlaceholder': 'DD',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'YYYY',
    'register.password': 'Password',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Create Account',
    'register.fillAllFields': 'Please fill in all fields',
    'register.passwordTooShort': 'Password must be at least 6 characters',
    'register.invalidBirthDate': 'Please enter a complete date of birth',
    'register.emailAlreadyRegistered': 'This email is already registered. Please sign in.',
    'register.invalidEmail': 'Please enter a valid email address',
    'register.weakPassword': 'Password is too weak. Use at least 6 characters.',
    'register.error': 'An error occurred',
    'register.successTitle': 'Registration Successful!',
    'register.successMessage': 'Your account has been created.{newline}You will be redirected to sign in...',
    'register.terms': 'By registering, you accept our',
    'register.termsOfService': 'Terms of Service',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',
    // Checkout Screen
    'checkout.title': 'Checkout',
    'checkout.guestData': 'Guest Data',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.email': 'Email Address',
    'checkout.notes': 'Notes (optional)',
    'checkout.pickupDate': 'Pickup Date',
    'checkout.pickupTime': 'Pickup Time',
    'checkout.selectTime': 'Select Time',
    'checkout.selectTimePlaceholder': 'Select time',
    'checkout.selectDate': 'Select Date',
    'checkout.continuePayment': 'Continue to Payment',
    'checkout.fillAllFields': 'Please fill in all fields',
    'checkout.selectDateFirst': 'Please select a date first',
    'checkout.selectTimeFirst': 'Please select a time',
    'checkout.invalidEmail': 'Please enter a valid email address',
    'checkout.timeUnit': '',
    'checkout.pickupInfo': 'Your order will be prepared fresh. Please be on time for pickup at Katharinengasse 14, Nuremberg.',
    // Order Success Screen
    'orderSuccess.paymentSuccess': 'Payment Successful!',
    'orderSuccess.thankYou': 'Thank you, {name}!',
    'orderSuccess.orderNumber': 'Order Number',
    'orderSuccess.confirmationSent': 'A confirmation has been sent to {email}',
    'orderSuccess.pickup': 'Pickup',
    'orderSuccess.pickupDate': 'Pickup Date',
    'orderSuccess.pickupTime': 'Time',
    'orderSuccess.pickupAddress': 'Pickup Address',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Nuremberg',
    'orderSuccess.newOrder': 'New Order',
    'orderSuccess.prepareToday': 'We are preparing your order fresh. See you soon!',
    'orderSuccess.prepareTomorrow': 'Your order will be prepared fresh tomorrow.',
    'orderSuccess.prepareLater': 'Your order will be prepared fresh on the pickup day.',
    // Payment Screen
    'payment.title': 'Payment',
    'payment.orderSummary': 'Order Summary',
    'payment.pickupDate': 'Pickup',
    'payment.amount': 'Total Amount',
    'payment.pay': 'Pay Now',
    'payment.error': 'Error',
    'payment.processing': 'Processing...',
    'payment.selectMethod': 'Choose your payment method',
    'payment.items': 'Items',
    'payment.time': 'Time',
    'payment.name': 'Name',
    'payment.securePayment': 'Secure Payment',
    'payment.creditCard': 'Credit Card via Stripe',
    'payment.sslEncrypted': 'SSL encrypted',
    'payment.pciCompliant': 'PCI compliant',
    'payment.allCards': 'All credit cards',
    'payment.stripeInfo': 'You will be redirected to the secure Stripe payment form. Your card data will be transmitted encrypted.',
    'payment.toPay': 'To pay',
    'payment.processingPayment': 'Processing payment...',
    // Reservation Screen
    'reservation.title': 'Reserve Table',
    'reservation.step1': 'Step 1: Date & Time',
    'reservation.step2': 'Step 2: Details',
    'reservation.selectDate': 'Select Date',
    'reservation.selectTime': 'Select Time',
    'reservation.time': 'Time',
    'reservation.guests': 'Number of Guests',
    'reservation.fullName': 'Full Name',
    'reservation.phone': 'Phone Number',
    'reservation.email': 'Email',
    'reservation.notes': 'Notes (optional)',
    'reservation.confirm': 'Confirm Reservation',
    'reservation.confirmed': 'Reservation Successful!',
    'reservation.confirmMessage': 'Your reservation has been confirmed. We look forward to your visit!',
    // Order History Screen
    'orderHistory.title': 'My Orders',
    'orderHistory.subtitle': 'Order History',
    'orderHistory.empty': 'No orders yet',
    'orderHistory.emptySubtext': 'Your orders will be displayed here',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.required': 'Required',
    // Weekdays
    'weekday.sunday': 'Sunday',
    'weekday.monday': 'Monday',
    'weekday.tuesday': 'Tuesday',
    'weekday.wednesday': 'Wednesday',
    'weekday.thursday': 'Thursday',
    'weekday.friday': 'Friday',
    'weekday.saturday': 'Saturday',
    // Weekdays Short
    'weekday.short.sunday': 'Sun',
    'weekday.short.monday': 'Mon',
    'weekday.short.tuesday': 'Tue',
    'weekday.short.wednesday': 'Wed',
    'weekday.short.thursday': 'Thu',
    'weekday.short.friday': 'Fri',
    'weekday.short.saturday': 'Sat',
    // Date Labels
    'date.today': 'Today',
    'date.tomorrow': 'Tomorrow',
    // Dish Detail
    'dish.quantity': 'Quantity',
    'dish.addToCart': 'Add to Cart',
    // Verify Email Screen
    'verify.title': 'Verify Email',
    'verify.enterCode': 'Enter Code',
    'verify.codeSentTo': 'We sent a 6-digit code to',
    'verify.sent': '',
    'verify.warning': 'Important: Do not close this screen! If you leave, you will have to register again.',
    'verify.confirm': 'Confirm',
    'verify.resendCode': 'Resend Code',
    'verify.enterCodeError': 'Please enter the 6-digit code',
    'verify.invalidCode': 'Invalid Code',
    'verify.emailConfirmed': 'Email confirmed! Signing in...',
    'verify.loginFailed': 'Sign in failed. Please sign in manually.',
    'verify.newCodeSent': 'New code has been sent!',
    'verify.codeNotSent': 'Could not resend code',
    'verify.cancelTitle': 'Cancel Registration?',
    'verify.cancelMessage': 'If you cancel now, you will have to register again. The unverified account will be deleted.',
    'verify.stayHere': 'Stay Here',
    'verify.cancelButton': 'Cancel',
    // Forgot Password Screen
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.heading': 'Forgot Password?',
    'forgotPassword.subtitle': 'Enter your email address and we will send you a link to reset your password.',
    'forgotPassword.email': 'Email',
    'forgotPassword.emailPlaceholder': 'your@email.com',
    'forgotPassword.sendLink': 'Send Link',
    'forgotPassword.backToLogin': 'Back to Sign In',
    'forgotPassword.enterEmail': 'Please enter your email address',
    'forgotPassword.invalidEmail': 'Please enter a valid email address',
    'forgotPassword.emailSent': 'Email sent! Check your inbox and click on the link.',
    'forgotPassword.error': 'An error occurred. Please try again later.',
    // Reset Password Screen
    'resetPassword.title': 'New Password',
    'resetPassword.heading': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.newPasswordPlaceholder': 'At least 6 characters',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.confirmPasswordPlaceholder': 'Repeat password',
    'resetPassword.changePassword': 'Change Password',
    'resetPassword.fillAllFields': 'Please fill in all fields',
    'resetPassword.passwordTooShort': 'Password must be at least 6 characters',
    'resetPassword.passwordMismatch': 'Passwords do not match',
    'resetPassword.success': 'Password has been successfully changed!',
    'resetPassword.error': 'An error occurred. Please try again.',
    // Login Checkout Screen
    'loginCheckout.title': 'Login',
    'loginCheckout.subtitle': 'Sign in',
    'loginCheckout.sectionTitle': 'Sign In',
    'loginCheckout.email': 'Email / Username',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Password',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Sign In & Continue',
    'loginCheckout.noAccount': 'No account yet?',
    'loginCheckout.createAccount': 'Create a free account now',
    'loginCheckout.accountInfo': 'With an account, you can view your order history and collect loyalty points.',
    'loginCheckout.fillAllFields': 'Please fill in all fields',
    'loginCheckout.invalidEmail': 'Please enter a valid email address',
    'loginCheckout.invalidCredentials': 'Email or password incorrect',
    'loginCheckout.total': 'Total',
    // Order History Screen - expand
    'orderHistory.noOrders': 'No orders yet',
    'orderHistory.orderCount': '{count} order',
    'orderHistory.ordersCount': '{count} orders',
    'orderHistory.emptyTitle': 'No Orders',
    'orderHistory.emptyDescription': 'You have not placed any orders yet',
    'orderHistory.orderNumber': 'Order #{number}',
    'orderHistory.pickup': 'Pickup',
    'orderHistory.items': 'Items',
    'orderHistory.total': 'Total',
    'orderHistory.statusPending': 'Pending',
    'orderHistory.statusConfirmed': 'Confirmed',
    'orderHistory.statusReady': 'Ready',
    'orderHistory.statusCompleted': 'Completed',
    'orderHistory.statusCancelled': 'Cancelled',
    'orderHistory.loadError': 'Error loading orders',
    // Help & Support Screen
    'helpSupport.title': 'Help & Support',
    'helpSupport.welcomeTitle': 'How can we help?',
    'helpSupport.welcomeSubtitle': 'Here you will find answers to frequently asked questions and our contact information',
    'helpSupport.faqTitle': 'Frequently Asked Questions',
    'helpSupport.contactTitle': 'Contact',
    'helpSupport.supportAvailable': 'Support Available',
    'helpSupport.supportHours': 'Mon-Fri: 9:00 AM - 6:00 PM{newline}Sat-Sun: 10:00 AM - 4:00 PM',
    'helpSupport.urgentTitle': 'Urgent Issues?',
    'helpSupport.urgentSubtitle': 'For urgent problems with your order, call us directly',
    'helpSupport.callNow': 'Call Now',
    'helpSupport.faq1Question': 'How can I place an order?',
    'helpSupport.faq1Answer': 'Select your desired dishes from the menu, add them to your cart, and proceed to checkout. You can choose between pickup and delivery.',
    'helpSupport.faq2Question': 'Which payment methods are accepted?',
    'helpSupport.faq2Answer': 'We accept credit cards, debit cards, and Apple Pay. All payments are securely processed through Stripe.',
    'helpSupport.faq3Question': 'How can I make a reservation?',
    'helpSupport.faq3Answer': 'Go to the Home tab and select "Reservation". Fill out the form and we will confirm your reservation via email.',
    'helpSupport.faq4Question': 'Can I cancel my order?',
    'helpSupport.faq4Answer': 'Orders can be cancelled up to 15 minutes after placement. Contact us directly through the app or by phone at 0911 63290791.',
    'helpSupport.faq5Question': 'How long does delivery take?',
    'helpSupport.faq5Answer': 'Delivery time is typically 30-45 minutes, depending on distance and current volume.',
    'helpSupport.faq6Question': 'What is the minimum order amount?',
    'helpSupport.faq6Answer': 'The minimum order amount is €15 for deliveries and €10 for pickups.',
    'helpSupport.phone': 'Phone',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'Email',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Address',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlin',
    'helpSupport.hours': 'Opening Hours',
    'helpSupport.hoursValue': 'Mon-Sun: 11:00 AM - 11:00 PM',
    // Imprint & Privacy Screens
    'imprint.title': 'Imprint',
    'privacy.title': 'Privacy',
    // Reservation Success Screen
    'reservationSuccess.title': 'Reservation Confirmed!',
    'reservationSuccess.thankYou': 'Thank you, {name}!',
    'reservationSuccess.reservationNumber': 'Reservation Number',
    'reservationSuccess.confirmationSent': 'A confirmation has been sent to {email}',
    'reservationSuccess.details': 'Reservation Details',
    'reservationSuccess.date': 'Date',
    'reservationSuccess.time': 'Time',
    'reservationSuccess.guests': 'Number of Guests',
    'reservationSuccess.person': 'person',
    'reservationSuccess.persons': 'persons',
    'reservationSuccess.restaurant': 'Restaurant',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Nuremberg',
    'reservationSuccess.backToHome': 'Back to Home',
  },
  vi: {
    // Vietnamese translations will be added here systematically
    // Phase 3.1: Profile & Account (14 Keys)
    'profile.edit': 'Chỉnh sửa hồ sơ',
    'profile.personalData': 'Dữ liệu cá nhân',
    'profile.updateInfo': 'Cập nhật thông tin tài khoản của bạn',
    'profile.firstName': 'Tên',
    'profile.firstNamePlaceholder': 'Tên của bạn',
    'profile.lastName': 'Họ',
    'profile.lastNamePlaceholder': 'Họ của bạn',
    'profile.email': 'Địa chỉ email',
    'profile.emailPlaceholder': 'email@cua.ban',
    'profile.language': 'Ngôn ngữ',
    'profile.languageSubtitle': 'Chọn ngôn ngữ ưa thích của bạn',
    'profile.save': 'Lưu thay đổi',
    'profile.saveSuccess': 'Cập nhật hồ sơ thành công!',
    'profile.emailInfo': 'Địa chỉ email của bạn sẽ được sử dụng để xác nhận đơn hàng và đặt bàn.',
    'profile.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'profile.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'profile.error': 'Lỗi',
    'profile.unexpectedError': 'Đã xảy ra lỗi không mong muốn',
    // Phase 3.2: Language Options (3 Keys)
    'language.german': 'Tiếng Đức',
    'language.english': 'Tiếng Anh',
    'language.vietnamese': 'Tiếng Việt',
    'language.spanish': 'Tiếng Tây Ban Nha',
    // Phase 3.3: Account Screen (20+ Keys)
    'account.title': 'Tài khoản',
    'account.subtitle': 'Quản lý hồ sơ của bạn',
    'account.guest': 'Khách',
    'account.notLoggedIn': 'Chưa đăng nhập',
    'account.loginNow': 'Đăng nhập ngay',
    'account.loginSuccess': 'Đăng nhập thành công!',
    'account.language': 'Ngôn ngữ',
    'account.languageSubtitle': 'Chọn ngôn ngữ ưa thích của bạn',
    'account.orders': 'Đơn hàng của tôi',
    'account.ordersSubtitle': 'Xem lịch sử đơn hàng',
    'account.editProfile': 'Chỉnh sửa hồ sơ',
    'account.editProfileSubtitle': 'Tên, Email, v.v.',
    'account.logout': 'Đăng xuất',
    'account.logoutConfirm': 'Bạn có thực sự muốn đăng xuất?',
    'account.cancel': 'Hủy',
    'account.comingSoon': 'Tính năng này sẽ sớm có sẵn',
    // Home Screen
    'home.heroTitle': 'Hai Thế Giới, Một Tầm Nhìn - Ẩm Thực Á Châu Được Tái Giải Thích',
    'home.heroSubtitle': 'Chào mừng đến thế giới nơi truyền thống gặp gỡ sự đổi mới',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan kết hợp hương vị đích thực từ quê hương Nam Trung Quốc với sự sáng tạo hiện đại. Được nuôi dưỡng bởi những khu chợ sôi động ở Quảng Châu, anh mang văn hóa ẩm thực hàng nghìn năm tuổi lên những đĩa nhỏ.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey mang nghệ thuật làm sushi đến Nuremberg. Với hơn 15 năm kinh nghiệm trong truyền thống Edomae, anh tạo ra từng món với sự tôn trọng sản phẩm và sự hoàn hảo của Nhật Bản.',
    'home.reserveTable': 'Đặt bàn',
    // Products Screen
    'products.title': 'Thực đơn',
    'products.subtitle': 'Khám phá các món ngon của chúng tôi',
    'products.highlights': 'Nổi bật',
    'products.smallDishes': 'Món nhỏ',
    'products.fusionSpecials': 'Đặc sản Fusion',
    'products.sushi': 'Sushi',
    'products.sides': 'Món phụ & Thêm',
    // Cart Screen
    'cart.title': 'Giỏ hàng',
    'cart.subtitle': 'Các món đã chọn của bạn',
    'cart.items': 'món',
    'cart.empty': 'Giỏ hàng của bạn trống',
    'cart.emptySubtext': 'Thêm sản phẩm để bắt đầu',
    'cart.clear': 'Xóa giỏ hàng',
    'cart.total': 'Tổng cộng',
    'cart.checkout': 'Thanh toán',
    // More Screen
    'more.title': 'Thêm',
    'more.subtitle': 'Tùy chọn bổ sung',
    'more.contact': 'Liên hệ',
    'more.contactSubtitle': 'Điện thoại, Email & Địa chỉ',
    'more.privacy': 'Quyền riêng tư',
    'more.privacySubtitle': 'Chính sách bảo mật',
    'more.imprint': 'Dấu ấn',
    'more.imprintSubtitle': 'Thông tin pháp lý',
    'more.appName': 'MOGGI App',
    'more.appSubtitle': 'Ứng dụng nhà hàng',
    'more.appVersion': 'Phiên bản 1.0.0',
    'more.comingSoon': 'Tính năng này sẽ sớm có sẵn',
    'more.info': 'Thông tin',
    // Navigation Tabs
    'nav.home': 'Trang chủ',
    'nav.menu': 'Thực đơn',
    'nav.cart': 'Giỏ hàng',
    'nav.account': 'Tài khoản',
    'nav.more': 'Thêm',
    // Contact Screen
    'contact.title': 'Liên hệ',
    'contact.phone': 'Điện thoại',
    'contact.location': 'Vị trí',
    'contact.email': 'Email',
    'contact.openingHours': 'Giờ mở cửa',
    'contact.copied': 'Đã sao chép',
    'contact.copiedMessage': '{label} đã được sao chép vào clipboard',
    'contact.copyError': 'Lỗi',
    'contact.monday': 'Thứ Hai:',
    'contact.tuesdayWednesday': 'Thứ Ba - Thứ Tư:',
    'contact.thursdaySaturday': 'Thứ Năm - Thứ Bảy:',
    'contact.sunday': 'Chủ Nhật:',
    'contact.closedDay': 'Đóng cửa',
    'contact.lunchService': 'Phục vụ trưa',
    'contact.eveningService': 'Phục vụ tối',
    'contact.copyErrorMessage': 'Không thể sao chép',
    // Product Categories
    'category.newIn': 'Mới',
    'category.businessLunch': 'Cơm trưa công sở',
    'category.tapasMeat': 'Tapas thịt',
    'category.tapasFish': 'Tapas cá',
    'category.tapasVegetarian': 'Tapas chay',
    'category.sticks': 'Xiên',
    'category.crisps': 'Giòn',
    'category.baos': 'Bánh bao',
    'category.noriTacos': 'Taco rong biển',
    'category.sashimi': 'Sashimi',
    'category.nigiri': 'Nigiri',
    'category.hosomaki': 'Hosomaki',
    'category.uramaki': 'Uramaki',
    'category.specialRoll': 'Cuộn đặc biệt',
    'category.crispyRolls': 'Cuộn giòn',
    'category.sides': 'Món phụ',
    // Login Screen
    'login.title': 'Đăng nhập',
    'login.sectionTitle': 'Đăng nhập',
    'login.emailLabel': 'Email / Tên người dùng',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Mật khẩu',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.button': 'Đăng nhập',
    'login.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'login.invalidCredentials': 'Email hoặc mật khẩu không chính xác',
    'login.emailNotConfirmed': 'Vui lòng xác nhận địa chỉ email của bạn',
    'login.error': 'Đã xảy ra lỗi',
    'login.noAccount': 'Chưa có tài khoản?',
    'login.registerNow': 'Tạo tài khoản miễn phí ngay',
    'login.accountInfo': 'Với tài khoản, bạn có thể xem lịch sử đơn hàng và tích điểm thưởng.',
    // Register Screen
    'register.title': 'Đăng ký',
    'register.pageTitle': 'Tạo tài khoản',
    'register.subtitle': 'Đăng ký để nhận ưu đãi độc quyền',
    'register.firstName': 'Tên',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Họ',
    'register.lastNamePlaceholder': 'Smith',
    'register.email': 'Email',
    'register.emailPlaceholder': 'your@email.com',
    'register.birthDate': 'Ngày sinh',
    'register.dayPlaceholder': 'DD',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'YYYY',
    'register.password': 'Mật khẩu',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Tạo tài khoản',
    'register.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'register.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
    'register.invalidBirthDate': 'Vui lòng nhập đầy đủ ngày sinh',
    'register.emailAlreadyRegistered': 'Email này đã được đăng ký. Vui lòng đăng nhập.',
    'register.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'register.weakPassword': 'Mật khẩu quá yếu. Sử dụng ít nhất 6 ký tự.',
    'register.error': 'Đã xảy ra lỗi',
    'register.successTitle': 'Đăng ký thành công!',
    'register.successMessage': 'Tài khoản của bạn đã được tạo.{newline}Bạn sẽ được chuyển hướng đến trang đăng nhập...',
    'register.terms': 'Bằng cách đăng ký, bạn chấp nhận',
    'register.termsOfService': 'Điều khoản dịch vụ',
    'register.and': 'và',
    'register.privacyPolicy': 'Chính sách bảo mật',
    // Verify Email Screen
    'verify.title': 'Xác minh Email',
    'verify.enterCode': 'Nhập mã',
    'verify.codeSentTo': 'Chúng tôi đã gửi mã 6 chữ số đến',
    'verify.sent': '',
    'verify.warning': 'Quan trọng: Đừng đóng màn hình này! Nếu rời đi, bạn sẽ phải đăng ký lại.',
    'verify.confirm': 'Xác nhận',
    'verify.resendCode': 'Gửi lại mã',
    'verify.enterCodeError': 'Vui lòng nhập mã 6 chữ số',
    'verify.invalidCode': 'Mã không hợp lệ',
    'verify.emailConfirmed': 'Email đã xác nhận! Đang đăng nhập...',
    'verify.loginFailed': 'Đăng nhập thất bại. Vui lòng đăng nhập thủ công.',
    'verify.newCodeSent': 'Mã mới đã được gửi!',
    'verify.codeNotSent': 'Không thể gửi lại mã',
    'verify.cancelTitle': 'Hủy đăng ký?',
    'verify.cancelMessage': 'Nếu bạn hủy bây giờ, bạn sẽ phải đăng ký lại. Tài khoản chưa xác minh sẽ bị xóa.',
    'verify.stayHere': 'Ở lại đây',
    'verify.cancelButton': 'Hủy',
    // Forgot Password Screen
    'forgotPassword.title': 'Đặt lại mật khẩu',
    'forgotPassword.heading': 'Quên mật khẩu?',
    'forgotPassword.subtitle': 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi link để đặt lại mật khẩu.',
    'forgotPassword.email': 'Email',
    'forgotPassword.emailPlaceholder': 'your@email.com',
    'forgotPassword.sendLink': 'Gửi link',
    'forgotPassword.backToLogin': 'Quay lại đăng nhập',
    'forgotPassword.enterEmail': 'Vui lòng nhập địa chỉ email của bạn',
    'forgotPassword.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'forgotPassword.emailSent': 'Email đã gửi! Kiểm tra hộp thư đến và nhấp vào link.',
    'forgotPassword.error': 'Đã xảy ra lỗi. Vui lòng thử lại sau.',
    // Reset Password Screen
    'resetPassword.title': 'Mật khẩu mới',
    'resetPassword.heading': 'Đặt lại mật khẩu',
    'resetPassword.subtitle': 'Nhập mật khẩu mới của bạn',
    'resetPassword.newPassword': 'Mật khẩu mới',
    'resetPassword.newPasswordPlaceholder': 'Ít nhất 6 ký tự',
    'resetPassword.confirmPassword': 'Xác nhận mật khẩu',
    'resetPassword.confirmPasswordPlaceholder': 'Nhập lại mật khẩu',
    'resetPassword.changePassword': 'Đổi mật khẩu',
    'resetPassword.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'resetPassword.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
    'resetPassword.passwordMismatch': 'Mật khẩu không khớp',
    'resetPassword.success': 'Mật khẩu đã được thay đổi thành công!',
    'resetPassword.error': 'Đã xảy ra lỗi. Vui lòng thử lại.',
    // Checkout Screen
    'checkout.title': 'Thanh toán',
    'checkout.guestData': 'Dữ liệu khách',
    'checkout.firstName': 'Tên',
    'checkout.lastName': 'Họ',
    'checkout.email': 'Địa chỉ Email',
    'checkout.notes': 'Ghi chú (tùy chọn)',
    'checkout.pickupDate': 'Ngày lấy hàng',
    'checkout.pickupTime': 'Giờ lấy hàng',
    'checkout.selectTime': 'Chọn giờ',
    'checkout.selectTimePlaceholder': 'Chọn giờ',
    'checkout.selectDate': 'Chọn ngày',
    'checkout.continuePayment': 'Tiếp tục thanh toán',
    'checkout.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'checkout.selectDateFirst': 'Vui lòng chọn ngày trước',
    'checkout.selectTimeFirst': 'Vui lòng chọn giờ',
    'checkout.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'checkout.timeUnit': '',
    'checkout.pickupInfo': 'Đơn hàng của bạn sẽ được chuẩn bị tươi. Vui lòng đến đúng giờ lấy hàng tại Katharinengasse 14, Nuremberg.',
    // Login Checkout Screen
    'loginCheckout.title': 'Đăng nhập',
    'loginCheckout.subtitle': 'Đăng nhập',
    'loginCheckout.sectionTitle': 'Đăng nhập',
    'loginCheckout.email': 'Email / Tên người dùng',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Mật khẩu',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Đăng nhập & Tiếp tục',
    'loginCheckout.noAccount': 'Chưa có tài khoản?',
    'loginCheckout.createAccount': 'Tạo tài khoản miễn phí ngay',
    'loginCheckout.accountInfo': 'Với tài khoản, bạn có thể xem lịch sử đơn hàng và tích điểm thưởng.',
    'loginCheckout.fillAllFields': 'Vui lòng điền đầy đủ tất cả các trường',
    'loginCheckout.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'loginCheckout.invalidCredentials': 'Email hoặc mật khẩu không chính xác',
    'loginCheckout.total': 'Tổng cộng',
    // Reservation Screen
    'reservation.title': 'Đặt bàn',
    'reservation.step1': 'Bước 1: Ngày & Giờ',
    'reservation.step2': 'Bước 2: Chi tiết',
    'reservation.selectDate': 'Chọn ngày',
    'reservation.selectTime': 'Chọn giờ',
    'reservation.time': 'Giờ',
    'reservation.guests': 'Số lượng khách',
    'reservation.fullName': 'Họ và tên đầy đủ',
    'reservation.phone': 'Số điện thoại',
    'reservation.email': 'Email',
    'reservation.notes': 'Ghi chú (tùy chọn)',
    'reservation.confirm': 'Xác nhận đặt bàn',
    'reservation.confirmed': 'Đặt bàn thành công!',
    'reservation.confirmMessage': 'Đặt bàn của bạn đã được xác nhận. Chúng tôi mong chờ chuyến thăm của bạn!',
    // Order Success Screen
    'orderSuccess.paymentSuccess': 'Thanh toán thành công!',
    'orderSuccess.thankYou': 'Cảm ơn, {name}!',
    'orderSuccess.orderNumber': 'Số đơn hàng',
    'orderSuccess.confirmationSent': 'Xác nhận đã được gửi đến {email}',
    'orderSuccess.pickup': 'Lấy hàng',
    'orderSuccess.pickupDate': 'Ngày lấy hàng',
    'orderSuccess.pickupTime': 'Giờ',
    'orderSuccess.pickupAddress': 'Địa chỉ lấy hàng',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Nuremberg',
    'orderSuccess.newOrder': 'Đơn hàng mới',
    'orderSuccess.prepareToday': 'Chúng tôi đang chuẩn bị đơn hàng tươi cho bạn. Hẹn gặp sớm!',
    'orderSuccess.prepareTomorrow': 'Đơn hàng của bạn sẽ được chuẩn bị tươi vào ngày mai.',
    'orderSuccess.prepareLater': 'Đơn hàng của bạn sẽ được chuẩn bị tươi vào ngày lấy hàng.',
    // Payment Screen
    'payment.title': 'Thanh toán',
    'payment.orderSummary': 'Tóm tắt đơn hàng',
    'payment.pickupDate': 'Lấy hàng',
    'payment.amount': 'Tổng số tiền',
    'payment.pay': 'Thanh toán ngay',
    'payment.error': 'Lỗi',
    'payment.processing': 'Đang xử lý...',
    'payment.selectMethod': 'Chọn phương thức thanh toán của bạn',
    'payment.items': 'Món',
    'payment.time': 'Giờ',
    'payment.name': 'Tên',
    'payment.securePayment': 'Thanh toán an toàn',
    'payment.creditCard': 'Thẻ tín dụng qua Stripe',
    'payment.sslEncrypted': 'Mã hóa SSL',
    'payment.pciCompliant': 'Tuân thủ PCI',
    'payment.allCards': 'Tất cả thẻ tín dụng',
    'payment.stripeInfo': 'Bạn sẽ được chuyển hướng đến biểu mẫu thanh toán Stripe an toàn. Dữ liệu thẻ của bạn sẽ được truyền đi được mã hóa.',
    'payment.toPay': 'Thanh toán',
    'payment.processingPayment': 'Đang xử lý thanh toán...',
    // Order History Screen
    'orderHistory.title': 'Đơn hàng của tôi',
    'orderHistory.subtitle': 'Lịch sử đơn hàng',
    'orderHistory.empty': 'Chưa có đơn hàng',
    'orderHistory.emptySubtext': 'Đơn hàng của bạn sẽ được hiển thị ở đây',
    'orderHistory.noOrders': 'Chưa có đơn hàng',
    'orderHistory.orderCount': '{count} đơn hàng',
    'orderHistory.ordersCount': '{count} đơn hàng',
    'orderHistory.emptyTitle': 'Không có đơn hàng',
    'orderHistory.emptyDescription': 'Bạn chưa đặt đơn hàng nào',
    'orderHistory.orderNumber': 'Đơn hàng #{number}',
    'orderHistory.pickup': 'Lấy hàng',
    'orderHistory.items': 'Món',
    'orderHistory.total': 'Tổng cộng',
    'orderHistory.statusPending': 'Đang chờ',
    'orderHistory.statusConfirmed': 'Đã xác nhận',
    'orderHistory.statusReady': 'Đã sẵn sàng',
    'orderHistory.statusCompleted': 'Đã hoàn thành',
    'orderHistory.statusCancelled': 'Đã hủy',
    'orderHistory.loadError': 'Lỗi khi tải đơn hàng',
    // Help & Support Screen
    'helpSupport.title': 'Trợ giúp & Hỗ trợ',
    'helpSupport.welcomeTitle': 'Chúng tôi có thể giúp gì?',
    'helpSupport.welcomeSubtitle': 'Tại đây bạn sẽ tìm thấy câu trả lời cho các câu hỏi thường gặp và thông tin liên hệ của chúng tôi',
    'helpSupport.faqTitle': 'Câu hỏi thường gặp',
    'helpSupport.contactTitle': 'Liên hệ',
    'helpSupport.supportAvailable': 'Hỗ trợ có sẵn',
    'helpSupport.supportHours': 'T2-T6: 9:00 SA - 6:00 CH{newline}T7-CN: 10:00 SA - 4:00 CH',
    'helpSupport.urgentTitle': 'Vấn đề khẩn cấp?',
    'helpSupport.urgentSubtitle': 'Đối với các vấn đề khẩn cấp về đơn hàng, hãy gọi trực tiếp cho chúng tôi',
    'helpSupport.callNow': 'Gọi ngay',
    'helpSupport.faq1Question': 'Làm thế nào để đặt hàng?',
    'helpSupport.faq1Answer': 'Chọn món ăn mong muốn từ thực đơn, thêm vào giỏ hàng và tiến hành thanh toán. Bạn có thể chọn lấy hàng hoặc giao hàng.',
    'helpSupport.faq2Question': 'Các phương thức thanh toán nào được chấp nhận?',
    'helpSupport.faq2Answer': 'Chúng tôi chấp nhận thẻ tín dụng, thẻ ghi nợ và Apple Pay. Tất cả thanh toán được xử lý an toàn qua Stripe.',
    'helpSupport.faq3Question': 'Làm thế nào để đặt bàn?',
    'helpSupport.faq3Answer': 'Đi đến tab Trang chủ và chọn "Đặt bàn". Điền vào biểu mẫu và chúng tôi sẽ xác nhận đặt bàn của bạn qua email.',
    'helpSupport.faq4Question': 'Tôi có thể hủy đơn hàng không?',
    'helpSupport.faq4Answer': 'Đơn hàng có thể được hủy trong vòng 15 phút sau khi đặt. Liên hệ với chúng tôi trực tiếp qua ứng dụng hoặc gọi 0911 63290791.',
    'helpSupport.faq5Question': 'Thời gian giao hàng là bao lâu?',
    'helpSupport.faq5Answer': 'Thời gian giao hàng thường là 30-45 phút, tùy thuộc vào khoảng cách và khối lượng hiện tại.',
    'helpSupport.faq6Question': 'Giá trị đơn hàng tối thiểu là bao nhiêu?',
    'helpSupport.faq6Answer': 'Giá trị đơn hàng tối thiểu là 15€ cho giao hàng và 10€ cho lấy hàng.',
    'helpSupport.phone': 'Điện thoại',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'Email',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Địa chỉ',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlin',
    'helpSupport.hours': 'Giờ mở cửa',
    'helpSupport.hoursValue': 'T2-CN: 11:00 SA - 11:00 CH',
    // Imprint & Privacy Screens
    'imprint.title': 'Dấu ấn',
    'privacy.title': 'Quyền riêng tư',
    // Reservation Success Screen
    'reservationSuccess.title': 'Đặt bàn đã được xác nhận!',
    'reservationSuccess.thankYou': 'Cảm ơn, {name}!',
    'reservationSuccess.reservationNumber': 'Số đặt bàn',
    'reservationSuccess.confirmationSent': 'Xác nhận đã được gửi đến {email}',
    'reservationSuccess.details': 'Chi tiết đặt bàn',
    'reservationSuccess.date': 'Ngày',
    'reservationSuccess.time': 'Giờ',
    'reservationSuccess.guests': 'Số lượng khách',
    'reservationSuccess.person': 'người',
    'reservationSuccess.persons': 'người',
    'reservationSuccess.restaurant': 'Nhà hàng',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Nuremberg',
    'reservationSuccess.backToHome': 'Quay lại Trang chủ',
    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.save': 'Lưu',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh sửa',
    'common.close': 'Đóng',
    'common.back': 'Quay lại',
    'common.next': 'Tiếp theo',
    'common.required': 'Bắt buộc',
    // Weekdays
    'weekday.sunday': 'Chủ Nhật',
    'weekday.monday': 'Thứ Hai',
    'weekday.tuesday': 'Thứ Ba',
    'weekday.wednesday': 'Thứ Tư',
    'weekday.thursday': 'Thứ Năm',
    'weekday.friday': 'Thứ Sáu',
    'weekday.saturday': 'Thứ Bảy',
    // Weekdays Short
    'weekday.short.sunday': 'CN',
    'weekday.short.monday': 'T2',
    'weekday.short.tuesday': 'T3',
    'weekday.short.wednesday': 'T4',
    'weekday.short.thursday': 'T5',
    'weekday.short.friday': 'T6',
    'weekday.short.saturday': 'T7',
    // Date Labels
    'date.today': 'Hôm nay',
    'date.tomorrow': 'Ngày mai',
    // Dish Detail
    'dish.quantity': 'Số lượng',
    'dish.addToCart': 'Thêm vào giỏ hàng',
  },
  es: {
    // Profile Edit Screen
    'profile.edit': 'Editar perfil',
    'profile.personalData': 'Datos personales',
    'profile.updateInfo': 'Actualiza la información de tu cuenta',
    'profile.firstName': 'Nombre',
    'profile.firstNamePlaceholder': 'Tu nombre',
    'profile.lastName': 'Apellido',
    'profile.lastNamePlaceholder': 'Tu apellido',
    'profile.email': 'Correo electrónico',
    'profile.emailPlaceholder': 'tu@email.com',
    'profile.language': 'Idioma',
    'profile.languageSubtitle': 'Elige tu idioma preferido',
    'profile.save': 'Guardar cambios',
    'profile.saveSuccess': '¡Perfil actualizado correctamente!',
    'profile.emailInfo': 'Tu dirección de correo electrónico se utiliza para confirmar pedidos y reservas.',
    'profile.fillAllFields': 'Por favor, rellena todos los campos',
    'profile.invalidEmail': 'Por favor, introduce una dirección de correo electrónico válida',
    'profile.error': 'Error',
    'profile.unexpectedError': 'Ha ocurrido un error inesperado',
    // Language Options
    'language.german': 'Alemán',
    'language.english': 'Inglés',
    'language.vietnamese': 'Vietnamita',
    'language.spanish': 'Español',
    // Account Screen
    'account.title': 'Cuenta',
    'account.subtitle': 'Gestiona tu perfil',
    'account.guest': 'Invitado',
    'account.notLoggedIn': 'No has iniciado sesión',
    'account.loginNow': 'Iniciar sesión ahora',
    'account.loginSuccess': '¡Inicio de sesión exitoso!',
    'account.language': 'Idioma',
    'account.languageSubtitle': 'Elige tu idioma preferido',
    'account.orders': 'Mis pedidos',
    'account.ordersSubtitle': 'Ver historial de pedidos',
    'account.editProfile': 'Editar perfil',
    'account.editProfileSubtitle': 'Nombre, correo electrónico, etc.',
    'account.logout': 'Cerrar sesión',
    'account.logoutConfirm': '¿Realmente quieres cerrar sesión?',
    'account.cancel': 'Cancelar',
    'account.comingSoon': 'Esta función estará disponible pronto',
    // Home Screen
    'home.heroTitle': 'Dos mundos, una visión - Cocina asiática reinterpretada',
    'home.heroSubtitle': 'Bienvenido a un mundo donde la tradición se encuentra con la innovación',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan combina los sabores auténticos de su hogar en el sur de China con creatividad moderna. Formado en los vibrantes mercados de Guangzhou, aporta una cultura culinaria milenaria en platos pequeños.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey trae el alto arte de la artesanía del sushi a Núremberg. Con más de 15 años de experiencia en la tradición Edomae, crea cada pieza con respeto por el producto y perfección japonesa.',
    'home.reserveTable': 'Reservar mesa',
    // Products Screen
    'products.title': 'Menú',
    'products.subtitle': 'Descubre nuestras delicias',
    'products.highlights': 'Destacados',
    'products.smallDishes': 'Platos Pequeños',
    'products.fusionSpecials': 'Especiales Fusión',
    'products.sushi': 'Sushi',
    'products.sides': 'Acompañamientos y más',
    // Cart Screen
    'cart.title': 'Carrito',
    'cart.subtitle': 'Tus artículos seleccionados',
    'cart.items': 'artículos',
    'cart.empty': 'Tu carrito está vacío',
    'cart.emptySubtext': 'Añade productos para comenzar',
    'cart.clear': 'Vaciar carrito',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al pago',
    // Checkout Screen
    'checkout.title': 'Pagar',
    'checkout.guestData': 'Datos del invitado',
    'checkout.firstName': 'Nombre',
    'checkout.lastName': 'Apellido',
    'checkout.email': 'Correo electrónico',
    'checkout.notes': 'Notas (opcional)',
    'checkout.pickupDate': 'Fecha de recogida',
    'checkout.pickupTime': 'Hora de recogida',
    'checkout.selectTime': 'Seleccionar hora',
    'checkout.selectTimePlaceholder': 'Seleccionar hora',
    'checkout.selectDate': 'Seleccionar fecha',
    'checkout.continuePayment': 'Continuar al pago',
    'checkout.fillAllFields': 'Por favor, rellena todos los campos',
    'checkout.selectDateFirst': 'Por favor, selecciona primero una fecha',
    'checkout.selectTimeFirst': 'Por favor, selecciona una hora',
    'checkout.invalidEmail': 'Por favor, introduce una dirección de correo electrónico válida',
    'checkout.timeUnit': '',
    'checkout.pickupInfo': 'Tu pedido se preparará fresco. Por favor, llega puntual a recogerlo en Katharinengasse 14, Núremberg.',
    // Order Success Screen
    'orderSuccess.paymentSuccess': '¡Pago exitoso!',
    'orderSuccess.thankYou': '¡Gracias, {name}!',
    'orderSuccess.orderNumber': 'Número de pedido',
    'orderSuccess.confirmationSent': 'Se ha enviado una confirmación a {email}',
    'orderSuccess.pickup': 'Recogida',
    'orderSuccess.pickupDate': 'Fecha de recogida',
    'orderSuccess.pickupTime': 'Hora',
    'orderSuccess.pickupAddress': 'Dirección de recogida',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Núremberg',
    'orderSuccess.newOrder': 'Nuevo pedido',
    'orderSuccess.prepareToday': 'Estamos preparando tu pedido fresco. ¡Hasta pronto!',
    'orderSuccess.prepareTomorrow': 'Tu pedido se preparará fresco mañana.',
    'orderSuccess.prepareLater': 'Tu pedido se preparará fresco el día de recogida.',
    // Common
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.done': 'Hecho',
    'common.skip': 'Omitir',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.submit': 'Enviar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',
    'common.add': 'Añadir',
    'common.remove': 'Eliminar',
    'common.update': 'Actualizar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.back': 'Atrás',
    'common.required': 'Obligatorio',
    // Login Screen
    'login.title': 'Iniciar sesión',
    'login.sectionTitle': 'Iniciar sesión',
    'login.emailLabel': 'Correo electrónico / Usuario',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Contraseña',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.button': 'Iniciar sesión',
    'login.fillAllFields': 'Por favor, rellena todos los campos',
    'login.invalidCredentials': 'Correo electrónico o contraseña incorrectos',
    'login.emailNotConfirmed': 'Por favor, confirma tu dirección de correo electrónico',
    'login.error': 'Ha ocurrido un error',
    'login.noAccount': '¿Aún no tienes cuenta?',
    'login.registerNow': 'Crea una cuenta gratuita ahora',
    'login.accountInfo': 'Con una cuenta, puedes ver tu historial de pedidos y acumular puntos de fidelidad.',
    // Register Screen
    'register.title': 'Registrarse',
    'register.pageTitle': 'Crear cuenta',
    'register.subtitle': 'Regístrate para obtener beneficios exclusivos',
    'register.firstName': 'Nombre',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Apellido',
    'register.lastNamePlaceholder': 'Smith',
    'register.email': 'Correo electrónico',
    'register.emailPlaceholder': 'tu@email.com',
    'register.birthDate': 'Fecha de nacimiento',
    'register.dayPlaceholder': 'DD',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'AAAA',
    'register.password': 'Contraseña',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Crear cuenta',
    'register.fillAllFields': 'Por favor, rellena todos los campos',
    'register.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'register.invalidBirthDate': 'Por favor, introduce una fecha de nacimiento completa',
    'register.emailAlreadyRegistered': 'Este correo electrónico ya está registrado. Por favor, inicia sesión.',
    'register.invalidEmail': 'Por favor, introduce una dirección de correo electrónico válida',
    'register.weakPassword': 'La contraseña es demasiado débil. Usa al menos 6 caracteres.',
    'register.error': 'Ha ocurrido un error',
    'register.successTitle': '¡Registro exitoso!',
    'register.successMessage': 'Tu cuenta ha sido creada.{newline}Serás redirigido al inicio de sesión...',
    'register.terms': 'Al registrarte, aceptas nuestros',
    'register.termsOfService': 'Términos de servicio',
    'register.and': 'y',
    'register.privacyPolicy': 'Política de privacidad',
    // Verify Email Screen
    'verify.title': 'Verificar correo',
    'verify.enterCode': 'Introduce el código',
    'verify.codeSentTo': 'Hemos enviado un código de 6 dígitos a',
    'verify.sent': '',
    'verify.warning': 'Importante: ¡No cierres esta pantalla! Si sales, tendrás que registrarte de nuevo.',
    'verify.confirm': 'Confirmar',
    'verify.resendCode': 'Reenviar código',
    'verify.enterCodeError': 'Por favor, introduce el código de 6 dígitos',
    'verify.invalidCode': 'Código inválido',
    'verify.emailConfirmed': 'Correo confirmado! Iniciando sesión...',
    'verify.loginFailed': 'Error al iniciar sesión. Por favor, inicia sesión manualmente.',
    'verify.newCodeSent': '¡Se ha enviado un nuevo código!',
    'verify.codeNotSent': 'No se pudo reenviar el código',
    'verify.cancelTitle': '¿Cancelar el registro?',
    'verify.cancelMessage': 'Si cancelas ahora, tendrás que registrarte de nuevo. La cuenta no verificada será eliminada.',
    'verify.stayHere': 'Permanecer aquí',
    'verify.cancelButton': 'Cancelar',
    // Forgot Password Screen
    'forgotPassword.title': 'Restablecer contraseña',
    'forgotPassword.heading': '¿Olvidaste tu contraseña?',
    'forgotPassword.subtitle': 'Introduce tu dirección de correo electrónico y te enviaremos un enlace para restablecer tu contraseña.',
    'forgotPassword.email': 'Correo electrónico',
    'forgotPassword.emailPlaceholder': 'tu@email.com',
    'forgotPassword.sendLink': 'Enviar enlace',
    'forgotPassword.backToLogin': 'Volver al inicio de sesión',
    'forgotPassword.enterEmail': 'Por favor, introduce tu dirección de correo electrónico',
    'forgotPassword.invalidEmail': 'Por favor, introduce una dirección de correo electrónico válida',
    'forgotPassword.emailSent': '¡Correo enviado! Revisa tu bandeja de entrada y haz clic en el enlace.',
    'forgotPassword.error': 'Ha ocurrido un error. Por favor, inténtalo de nuevo más tarde.',
    // Reset Password Screen
    'resetPassword.title': 'Nueva contraseña',
    'resetPassword.heading': 'Restablecer contraseña',
    'resetPassword.subtitle': 'Introduce tu nueva contraseña',
    'resetPassword.newPassword': 'Nueva contraseña',
    'resetPassword.newPasswordPlaceholder': 'Mínimo 6 caracteres',
    'resetPassword.confirmPassword': 'Confirmar contraseña',
    'resetPassword.confirmPasswordPlaceholder': 'Repite la contraseña',
    'resetPassword.changePassword': 'Cambiar contraseña',
    'resetPassword.fillAllFields': 'Por favor, rellena todos los campos',
    'resetPassword.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'resetPassword.passwordMismatch': 'Las contraseñas no coinciden',
    'resetPassword.success': '¡La contraseña ha sido cambiada correctamente!',
    'resetPassword.error': 'Ha ocurrido un error. Por favor, inténtalo de nuevo.',
    // Payment Screen
    'payment.title': 'Pago',
    'payment.orderSummary': 'Resumen del pedido',
    'payment.pickupDate': 'Recogida',
    'payment.amount': 'Importe total',
    'payment.pay': 'Pagar ahora',
    'payment.error': 'Error',
    'payment.processing': 'Procesando...',
    'payment.selectMethod': 'Elige tu método de pago',
    'payment.items': 'Artículos',
    'payment.time': 'Hora',
    'payment.name': 'Nombre',
    'payment.securePayment': 'Pago seguro',
    'payment.creditCard': 'Tarjeta de crédito vía Stripe',
    'payment.sslEncrypted': 'Encriptación SSL',
    'payment.pciCompliant': 'Cumple con PCI',
    'payment.allCards': 'Todas las tarjetas de crédito',
    'payment.stripeInfo': 'Serás redirigido al formulario de pago seguro de Stripe. Los datos de tu tarjeta se transmitirán encriptados.',
    'payment.toPay': 'A pagar',
    'payment.processingPayment': 'Procesando pago...',
    // Order History Screen
    'orderHistory.title': 'Mis Pedidos',
    'orderHistory.subtitle': 'Historial de pedidos',
    'orderHistory.empty': 'Aún no hay pedidos',
    'orderHistory.emptySubtext': 'Tus pedidos se mostrarán aquí',
    'orderHistory.noOrders': 'Aún no hay pedidos',
    'orderHistory.orderCount': '{count} pedido',
    'orderHistory.ordersCount': '{count} pedidos',
    'orderHistory.emptyTitle': 'Sin pedidos',
    'orderHistory.emptyDescription': 'Aún no has realizado ningún pedido',
    'orderHistory.orderNumber': 'Pedido #{number}',
    'orderHistory.pickup': 'Recogida',
    'orderHistory.items': 'Artículos',
    'orderHistory.total': 'Total',
    'orderHistory.statusPending': 'Pendiente',
    'orderHistory.statusConfirmed': 'Confirmado',
    'orderHistory.statusReady': 'Listo',
    'orderHistory.statusCompleted': 'Completado',
    'orderHistory.statusCancelled': 'Cancelado',
    'orderHistory.loadError': 'Error al cargar los pedidos',
    // Reservation Screen
    'reservation.title': 'Reservar mesa',
    'reservation.step1': 'Paso 1: Fecha y hora',
    'reservation.step2': 'Paso 2: Detalles',
    'reservation.selectDate': 'Seleccionar fecha',
    'reservation.selectTime': 'Seleccionar hora',
    'reservation.time': 'Hora',
    'reservation.guests': 'Número de personas',
    'reservation.fullName': 'Nombre completo',
    'reservation.phone': 'Número de teléfono',
    'reservation.email': 'Correo electrónico',
    'reservation.notes': 'Observaciones (opcional)',
    'reservation.confirm': 'Confirmar reserva',
    'reservation.confirmed': '¡Reserva exitosa!',
    'reservation.confirmMessage': 'Tu reserva ha sido confirmada. ¡Esperamos tu visita!',
    // More Screen
    'more.title': 'Más',
    'more.subtitle': 'Opciones adicionales',
    'more.contact': 'Contacto',
    'more.contactSubtitle': 'Teléfono, correo electrónico y dirección',
    'more.privacy': 'Privacidad',
    'more.privacySubtitle': 'Política de privacidad',
    'more.imprint': 'Aviso legal',
    'more.imprintSubtitle': 'Información legal',
    'more.appName': 'App MOGGI',
    'more.appSubtitle': 'App de restaurante',
    'more.appVersion': 'Versión 1.0.0',
    'more.comingSoon': 'Esta función estará disponible pronto',
    'more.info': 'Info',
    // Navigation Tabs
    'nav.home': 'Inicio',
    'nav.menu': 'Menú',
    'nav.cart': 'Carrito',
    'nav.account': 'Cuenta',
    'nav.more': 'Más',
    // Contact Screen
    'contact.title': 'Contacto',
    'contact.phone': 'Teléfono',
    'contact.location': 'Ubicación',
    'contact.email': 'Correo electrónico',
    'contact.openingHours': 'Horario de apertura',
    'contact.copied': 'Copiado',
    'contact.copiedMessage': '{label} se ha copiado al portapapeles',
    'contact.copyError': 'Error',
    'contact.monday': 'Lunes:',
    'contact.tuesdayWednesday': 'Martes - Miércoles:',
    'contact.thursdaySaturday': 'Jueves - Sábado:',
    'contact.sunday': 'Domingo:',
    'contact.closedDay': 'Cerrado',
    'contact.lunchService': 'Servicio de comida',
    'contact.eveningService': 'Servicio de cena',
    // Product Categories
    'category.newIn': 'Novedades',
    'category.businessLunch': 'Almuerzo de negocios',
    'category.tapasMeat': 'Tapas de carne',
    'category.tapasFish': 'Tapas de pescado',
    'category.tapasVegetarian': 'Tapas vegetarianas',
    'category.sticks': 'Brochetas',
    'category.crisps': 'Crujientes',
    'category.baos': 'Baos',
    'category.noriTacos': 'Tacos Nori',
    'category.sashimi': 'Sashimi',
    'category.nigiri': 'Nigiri',
    'category.hosomaki': 'Hosomaki',
    'category.uramaki': 'Uramaki',
    'category.specialRoll': 'Special Roll',
    'category.crispyRolls': 'Crispy Rolls',
    'category.sides': 'Acompañamientos',
    'contact.copyErrorMessage': 'No se pudo copiar',
    // Help & Support Screen
    'helpSupport.title': 'Ayuda y Soporte',
    'helpSupport.welcomeTitle': '¿Cómo podemos ayudarte?',
    'helpSupport.welcomeSubtitle': 'Aquí encontrarás respuestas a preguntas frecuentes y nuestra información de contacto',
    'helpSupport.faqTitle': 'Preguntas frecuentes',
    'helpSupport.contactTitle': 'Contacto',
    'helpSupport.supportAvailable': 'Soporte disponible',
    'helpSupport.supportHours': 'Lun-Vie: 9:00 - 18:00{newline}Sáb-Dom: 10:00 - 16:00',
    'helpSupport.urgentTitle': '¿Problemas urgentes?',
    'helpSupport.urgentSubtitle': 'Para problemas urgentes con tu pedido, llámanos directamente',
    'helpSupport.callNow': 'Llamar ahora',
    'helpSupport.faq1Question': '¿Cómo puedo hacer un pedido?',
    'helpSupport.faq1Answer': 'Selecciona los platos deseados del menú, añádelos al carrito y procede al pago. Puedes elegir entre recogida y entrega.',
    'helpSupport.faq2Question': '¿Qué métodos de pago se aceptan?',
    'helpSupport.faq2Answer': 'Aceptamos tarjetas de crédito, tarjetas de débito y Apple Pay. Todos los pagos se procesan de forma segura a través de Stripe.',
    'helpSupport.faq3Question': '¿Cómo puedo hacer una reserva?',
    'helpSupport.faq3Answer': 'Ve a la pestaña Inicio y selecciona "Reservar". Rellena el formulario y confirmaremos tu reserva por correo electrónico.',
    'helpSupport.faq4Question': '¿Puedo cancelar mi pedido?',
    'helpSupport.faq4Answer': 'Los pedidos se pueden cancelar hasta 15 minutos después de realizarlos. Contáctanos directamente a través de la app o por teléfono al 0911 63290791.',
    'helpSupport.faq5Question': '¿Cuánto tarda la entrega?',
    'helpSupport.faq5Answer': 'El tiempo de entrega es normalmente de 30-45 minutos, dependiendo de la distancia y el volumen actual.',
    'helpSupport.faq6Question': '¿Cuál es el importe mínimo del pedido?',
    'helpSupport.faq6Answer': 'El importe mínimo del pedido es de 15€ para entregas y 10€ para recogidas.',
    'helpSupport.phone': 'Teléfono',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'Correo electrónico',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Dirección',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlín',
    'helpSupport.hours': 'Horario de apertura',
    'helpSupport.hoursValue': 'Lun-Dom: 11:00 - 23:00',
    // Imprint & Privacy Screens
    'imprint.title': 'Aviso legal',
    'privacy.title': 'Privacidad',
    // Reservation Success Screen
    'reservationSuccess.title': '¡Reserva confirmada!',
    'reservationSuccess.thankYou': '¡Gracias, {name}!',
    'reservationSuccess.reservationNumber': 'Número de reserva',
    'reservationSuccess.confirmationSent': 'Se ha enviado una confirmación a {email}',
    'reservationSuccess.details': 'Detalles de la reserva',
    'reservationSuccess.date': 'Fecha',
    'reservationSuccess.time': 'Hora',
    'reservationSuccess.guests': 'Número de personas',
    'reservationSuccess.person': 'persona',
    'reservationSuccess.persons': 'personas',
    'reservationSuccess.restaurant': 'Restaurante',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Núremberg',
    'reservationSuccess.backToHome': 'Volver al inicio',
    // Login Checkout Screen
    'loginCheckout.title': 'Iniciar sesión',
    'loginCheckout.subtitle': 'Inicia sesión',
    'loginCheckout.sectionTitle': 'Iniciar sesión',
    'loginCheckout.email': 'Correo electrónico / Nombre de usuario',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Contraseña',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Iniciar sesión y continuar',
    'loginCheckout.noAccount': '¿Aún no tienes cuenta?',
    'loginCheckout.createAccount': 'Crea una cuenta gratuita ahora',
    'loginCheckout.accountInfo': 'Con una cuenta, puedes ver tu historial de pedidos y acumular puntos de fidelidad.',
    'loginCheckout.fillAllFields': 'Por favor, rellena todos los campos',
    'loginCheckout.invalidEmail': 'Por favor, introduce una dirección de correo electrónico válida',
    'loginCheckout.invalidCredentials': 'Correo electrónico o contraseña incorrectos',
    'loginCheckout.total': 'Total',
    // Weekdays
    'weekday.sunday': 'Domingo',
    'weekday.monday': 'Lunes',
    'weekday.tuesday': 'Martes',
    'weekday.wednesday': 'Miércoles',
    'weekday.thursday': 'Jueves',
    'weekday.friday': 'Viernes',
    'weekday.saturday': 'Sábado',
    // Weekdays Short
    'weekday.short.sunday': 'Dom',
    'weekday.short.monday': 'Lun',
    'weekday.short.tuesday': 'Mar',
    'weekday.short.wednesday': 'Mié',
    'weekday.short.thursday': 'Jue',
    'weekday.short.friday': 'Vie',
    'weekday.short.saturday': 'Sáb',
    // Date Labels
    'date.today': 'Hoy',
    'date.tomorrow': 'Mañana',
    // Dish Detail
    'dish.quantity': 'Cantidad',
    'dish.addToCart': 'Añadir al carrito',
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('de');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load saved language from AsyncStorage
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(STORAGE_KEY);
        if (savedLanguage && (savedLanguage === 'de' || savedLanguage === 'en' || savedLanguage === 'vi' || savedLanguage === 'es')) {
          setLanguageState(savedLanguage as Language);
        }
      } catch (error) {
        console.error('Error loading language:', error);
      } finally {
        setLoading(false);
      }
    };

    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    
    // Ersetze Platzhalter wie {name}, {email}, etc.
    if (params) {
      Object.keys(params).forEach((param) => {
        text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
      });
    }
    
    // Ersetze {newline} mit \n
    text = text.replace(/\{newline\}/g, '\n');
    
    return text;
  };

  const getCategoryTitle = (categoryName: string): string => {
    return menuTranslations[language]?.categories[categoryName]?.title || categoryName;
  };

  const getCategorySubtitle = (categoryName: string): string => {
    return menuTranslations[language]?.categories[categoryName]?.subtitle || '';
  };

  const getDishDescription = (dishName: string): string => {
    return menuTranslations[language]?.dishes[dishName] || '';
  };

  const getTagTranslation = (tag: string): string => {
    return menuTranslations[language]?.tags[tag] || tag;
  };

  const getWeekdayNames = (): string[] => {
    return [
      t('weekday.sunday'),
      t('weekday.monday'),
      t('weekday.tuesday'),
      t('weekday.wednesday'),
      t('weekday.thursday'),
      t('weekday.friday'),
      t('weekday.saturday'),
    ];
  };

  const getShortWeekdayNames = (): string[] => {
    return [
      t('weekday.short.sunday'),
      t('weekday.short.monday'),
      t('weekday.short.tuesday'),
      t('weekday.short.wednesday'),
      t('weekday.short.thursday'),
      t('weekday.short.friday'),
      t('weekday.short.saturday'),
    ];
  };

  // Don't render children until language is loaded
  if (loading) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCategoryTitle, getCategorySubtitle, getDishDescription, getTagTranslation, getWeekdayNames, getShortWeekdayNames }}>
      {children}
    </LanguageContext.Provider>
  );
};
