import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { menuTranslations } from '../translations/menuTranslations';

export type Language = 'de' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, params?: Record<string, string>) => string;
  getCategoryTitle: (categoryName: string) => string;
  getCategorySubtitle: (categoryName: string) => string;
  getDishDescription: (dishName: string) => string;
  getTagTranslation: (tag: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = '@moggi_app_language';

// Übersetzungen
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Profile Edit Screen
    'profile.edit': 'Profil bearbeiten',
    'profile.personalData': 'Persönliche Daten',
    'profile.updateInfo': 'Aktualisiere deine Kontoinformationen',
    'profile.firstName': 'Vorname',
    'profile.firstNamePlaceholder': 'Dein Vorname',
    'profile.lastName': 'Nachname',
    'profile.lastNamePlaceholder': 'Dein Nachname',
    'profile.email': 'E-Mail-Adresse',
    'profile.emailPlaceholder': 'deine@email.com',
    'profile.language': 'Sprache',
    'profile.languageSubtitle': 'Wähle deine bevorzugte Sprache',
    'profile.save': 'Änderungen speichern',
    'profile.saveSuccess': 'Profil erfolgreich aktualisiert!',
    'profile.emailInfo': 'Deine E-Mail-Adresse wird für die Bestätigung von Bestellungen und Reservierungen verwendet.',
    'profile.fillAllFields': 'Bitte fülle alle Felder aus',
    'profile.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'profile.error': 'Fehler',
    'profile.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten',
    // Language Options
    'language.german': 'Deutsch',
    'language.english': 'English',
    // Account Screen
    'account.title': 'Konto',
    'account.subtitle': 'Verwalte dein Profil',
    'account.guest': 'Gast',
    'account.notLoggedIn': 'Noch nicht angemeldet',
    'account.loginNow': 'Jetzt anmelden',
    'account.loginSuccess': 'Erfolgreich angemeldet!',
    'account.language': 'Sprache',
    'account.languageSubtitle': 'Wähle deine bevorzugte Sprache',
    'account.orders': 'Meine Bestellungen',
    'account.ordersSubtitle': 'Bestellhistorie ansehen',
    'account.editProfile': 'Profil bearbeiten',
    'account.editProfileSubtitle': 'Name, E-Mail, etc.',
    'account.logout': 'Abmelden',
    'account.logoutConfirm': 'Möchtest du dich wirklich abmelden?',
    'account.cancel': 'Abbrechen',
    'account.comingSoon': 'Diese Funktion wird bald verfügbar sein',
    // Home Screen
    'home.heroTitle': 'Zwei Welten, eine Vision - Asiatische Küche neu interpretiert',
    'home.heroSubtitle': 'Willkommen in einer Welt, wo Tradition auf Innovation trifft',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan verbindet die authentischen Aromen seiner südchinesischen Heimat mit moderner Kreativität. Geprägt von den lebendigen Märkten Guangzhous, bringt er jahrtausendealte Esskultur auf kleine Teller.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey bringt die hohe Kunst des Sushi-Handwerks nach Nürnberg. Mit über 15 Jahren Erfahrung in der Edomae-Tradition erschafft er jedes Stück mit Respekt für das Produkt und japanischer Perfektion.',
    'home.reserveTable': 'Tisch reservieren',
    // Products Screen
    'products.title': 'Speisekarte',
    'products.subtitle': 'Entdecke unsere Köstlichkeiten',
    'products.highlights': 'Highlights',
    'products.smallDishes': 'Kleine Gerichte',
    'products.fusionSpecials': 'Fusion Specials',
    'products.sushi': 'Sushi',
    'products.sides': 'Beilagen & More',
    // Cart Screen
    'cart.title': 'Warenkorb',
    'cart.subtitle': 'Deine ausgewählten Artikel',
    'cart.items': 'Artikel',
    'cart.empty': 'Dein Warenkorb ist leer',
    'cart.emptySubtext': 'Füge Produkte hinzu, um loszulegen',
    'cart.clear': 'Warenkorb leeren',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    // More Screen
    'more.title': 'Mehr',
    'more.subtitle': 'Weitere Optionen',
    'more.contact': 'Kontakt',
    'more.contactSubtitle': 'Telefon, E-Mail & Adresse',
    'more.privacy': 'Datenschutz',
    'more.privacySubtitle': 'Datenschutzerklärung',
    'more.imprint': 'Impressum',
    'more.imprintSubtitle': 'Rechtliche Informationen',
    'more.appName': 'MOGGI App',
    'more.appSubtitle': 'Restaurant-App',
    'more.appVersion': 'Version 1.0.0',
    'more.comingSoon': 'Diese Funktion wird bald verfügbar sein',
    'more.info': 'Info',
    // Navigation Tabs
    'nav.home': 'Home',
    'nav.menu': 'Speisekarte',
    'nav.cart': 'Warenkorb',
    'nav.account': 'Konto',
    'nav.more': 'Mehr',
    // Contact Screen
    'contact.title': 'Kontakt',
    'contact.phone': 'Telefon',
    'contact.location': 'Standort',
    'contact.email': 'E-Mail',
    'contact.openingHours': 'Öffnungszeiten',
    'contact.copied': 'Kopiert',
    'contact.copiedMessage': '{label} wurde in die Zwischenablage kopiert',
    'contact.copyError': 'Fehler',
    'contact.copyErrorMessage': 'Konnte nicht kopiert werden',
    // Login Screen
    'login.title': 'Login',
    'login.sectionTitle': 'Anmeldung',
    'login.emailLabel': 'E-Mail / Benutzername',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Passwort',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Passwort vergessen?',
    'login.button': 'Anmelden',
    'login.fillAllFields': 'Bitte fülle alle Felder aus',
    'login.invalidCredentials': 'E-Mail oder Passwort ist falsch',
    'login.emailNotConfirmed': 'Bitte bestätige deine E-Mail-Adresse',
    'login.error': 'Ein Fehler ist aufgetreten',
    'login.noAccount': 'Noch kein Account?',
    'login.registerNow': 'Erstelle jetzt kostenlos einen Account',
    'login.accountInfo': 'Mit einem Account kannst du deine Bestellhistorie einsehen und Treuepunkte sammeln.',
    // Register Screen
    'register.title': 'Registrieren',
    'register.pageTitle': 'Konto erstellen',
    'register.subtitle': 'Registrierung für exklusive Vorteile',
    'register.firstName': 'Vorname',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Nachname',
    'register.lastNamePlaceholder': 'Mustermann',
    'register.email': 'E-Mail',
    'register.emailPlaceholder': 'deine@email.com',
    'register.birthDate': 'Geburtsdatum',
    'register.dayPlaceholder': 'TT',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'JJJJ',
    'register.password': 'Passwort',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Konto erstellen',
    'register.fillAllFields': 'Bitte fülle alle Felder aus',
    'register.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein',
    'register.invalidBirthDate': 'Bitte gib ein vollständiges Geburtsdatum ein',
    'register.emailAlreadyRegistered': 'Diese E-Mail ist bereits registriert. Bitte melde dich an.',
    'register.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'register.weakPassword': 'Passwort ist zu schwach. Verwende mindestens 6 Zeichen.',
    'register.error': 'Ein Fehler ist aufgetreten',
    'register.successTitle': 'Registrierung erfolgreich!',
    'register.successMessage': 'Dein Konto wurde erstellt.{newline}Du wirst zur Anmeldung weitergeleitet...',
    'register.terms': 'Mit der Registrierung akzeptierst du unsere',
    'register.termsOfService': 'Nutzungsbedingungen',
    'register.and': 'und',
    'register.privacyPolicy': 'Datenschutzrichtlinien',
    // Checkout Screen
    'checkout.title': 'Checkout',
    'checkout.guestData': 'Gast-Daten',
    'checkout.firstName': 'Vorname',
    'checkout.lastName': 'Nachname',
    'checkout.email': 'E-Mail-Adresse',
    'checkout.notes': 'Hinweise (optional)',
    'checkout.pickupDate': 'Abholdatum',
    'checkout.pickupTime': 'Abholzeit',
    'checkout.selectTime': 'Uhrzeit auswählen',
    'checkout.selectTimePlaceholder': 'Uhrzeit wählen',
    'checkout.selectDate': 'Datum auswählen',
    'checkout.continuePayment': 'Weiter zur Zahlung',
    'checkout.fillAllFields': 'Bitte fülle alle Felder aus',
    'checkout.selectDateFirst': 'Bitte wähle erst ein Datum aus',
    'checkout.selectTimeFirst': 'Bitte wähle eine Uhrzeit aus',
    'checkout.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'checkout.timeUnit': 'Uhr',
    'checkout.pickupInfo': 'Deine Bestellung wird frisch zubereitet. Bitte sei pünktlich zur Abholzeit bei uns in der Katharinengasse 14, Nürnberg.',
    // Order Success Screen
    'orderSuccess.paymentSuccess': 'Zahlung erfolgreich!',
    'orderSuccess.thankYou': 'Vielen Dank, {name}!',
    'orderSuccess.orderNumber': 'Bestellnummer',
    'orderSuccess.confirmationSent': 'Eine Bestätigung wurde an {email} gesendet',
    'orderSuccess.pickup': 'Abholung',
    'orderSuccess.pickupDate': 'Abholdatum',
    'orderSuccess.pickupTime': 'Uhrzeit',
    'orderSuccess.pickupAddress': 'Abholadresse',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Nürnberg',
    'orderSuccess.newOrder': 'Weitere Bestellung',
    'orderSuccess.prepareToday': 'Wir bereiten deine Bestellung frisch zu. Bis gleich!',
    'orderSuccess.prepareTomorrow': 'Deine Bestellung wird morgen frisch zubereitet.',
    'orderSuccess.prepareLater': 'Deine Bestellung wird am Abholtag frisch zubereitet.',
    // Payment Screen
    'payment.title': 'Zahlung',
    'payment.orderSummary': 'Bestellübersicht',
    'payment.pickupDate': 'Abholung',
    'payment.amount': 'Gesamtbetrag',
    'payment.pay': 'Jetzt bezahlen',
    'payment.error': 'Fehler',
    'payment.processing': 'Wird verarbeitet...',
    'payment.selectMethod': 'Wähle deine Zahlungsmethode',
    'payment.items': 'Artikel',
    'payment.time': 'Uhrzeit',
    'payment.name': 'Name',
    'payment.securePayment': 'Sichere Zahlung',
    'payment.creditCard': 'Kreditkarte via Stripe',
    'payment.sslEncrypted': 'SSL-verschlüsselt',
    'payment.pciCompliant': 'PCI-konform',
    'payment.allCards': 'Alle Kreditkarten',
    'payment.stripeInfo': 'Du wirst zum sicheren Stripe-Zahlungsformular weitergeleitet. Deine Kartendaten werden verschlüsselt übertragen.',
    'payment.toPay': 'Zu zahlen',
    'payment.processingPayment': 'Verarbeite Zahlung...',
    // Reservation Screen
    'reservation.title': 'Tisch reservieren',
    'reservation.step1': 'Schritt 1: Datum & Uhrzeit',
    'reservation.step2': 'Schritt 2: Details',
    'reservation.selectDate': 'Datum auswählen',
    'reservation.selectTime': 'Uhrzeit auswählen',
    'reservation.time': 'Uhrzeit',
    'reservation.guests': 'Anzahl Gäste',
    'reservation.fullName': 'Vollständiger Name',
    'reservation.phone': 'Telefonnummer',
    'reservation.email': 'E-Mail',
    'reservation.notes': 'Anmerkungen (optional)',
    'reservation.confirm': 'Reservierung bestätigen',
    'reservation.confirmed': 'Reservierung erfolgreich!',
    'reservation.confirmMessage': 'Deine Reservierung wurde bestätigt. Wir freuen uns auf deinen Besuch!',
    // Order History Screen
    'orderHistory.title': 'Meine Bestellungen',
    'orderHistory.subtitle': 'Bestellhistorie',
    'orderHistory.empty': 'Noch keine Bestellungen',
    'orderHistory.emptySubtext': 'Deine Bestellungen werden hier angezeigt',
    // Dish Detail
    'dish.quantity': 'Menge',
    'dish.addToCart': 'In den Warenkorb',
    // Verify Email Screen
    'verify.title': 'E-Mail bestätigen',
    'verify.enterCode': 'Code eingeben',
    'verify.codeSentTo': 'Wir haben einen 6-stelligen Code an',
    'verify.sent': 'gesendet.',
    'verify.warning': 'Wichtig: Schließe diesen Screen nicht! Bei Verlassen musst du dich neu registrieren.',
    'verify.confirm': 'Bestätigen',
    'verify.resendCode': 'Code erneut senden',
    'verify.enterCodeError': 'Bitte gib den 6-stelligen Code ein',
    'verify.invalidCode': 'Ungültiger Code',
    'verify.emailConfirmed': 'E-Mail bestätigt! Melde dich an...',
    'verify.loginFailed': 'Anmeldung fehlgeschlagen. Bitte melde dich manuell an.',
    'verify.newCodeSent': 'Neuer Code wurde gesendet!',
    'verify.codeNotSent': 'Code konnte nicht erneut gesendet werden',
    'verify.cancelTitle': 'Registrierung abbrechen?',
    'verify.cancelMessage': 'Wenn du jetzt abbrichst, musst du dich neu registrieren. Der unbestätigte Account wird gelöscht.',
    'verify.stayHere': 'Hier bleiben',
    'verify.cancelButton': 'Abbrechen',
    // Forgot Password Screen
    'forgotPassword.title': 'Passwort zurücksetzen',
    'forgotPassword.heading': 'Passwort vergessen?',
    'forgotPassword.subtitle': 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.',
    'forgotPassword.email': 'E-Mail',
    'forgotPassword.emailPlaceholder': 'deine@email.com',
    'forgotPassword.sendLink': 'Link senden',
    'forgotPassword.backToLogin': 'Zurück zur Anmeldung',
    'forgotPassword.enterEmail': 'Bitte gib deine E-Mail-Adresse ein',
    'forgotPassword.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'forgotPassword.emailSent': 'E-Mail versendet! Prüfe deinen Posteingang und klicke auf den Link.',
    'forgotPassword.error': 'Ein Fehler ist aufgetreten. Bitte versuche es später erneut.',
    // Reset Password Screen
    'resetPassword.title': 'Neues Passwort',
    'resetPassword.heading': 'Passwort zurücksetzen',
    'resetPassword.subtitle': 'Gib dein neues Passwort ein',
    'resetPassword.newPassword': 'Neues Passwort',
    'resetPassword.newPasswordPlaceholder': 'Mindestens 6 Zeichen',
    'resetPassword.confirmPassword': 'Passwort bestätigen',
    'resetPassword.confirmPasswordPlaceholder': 'Passwort wiederholen',
    'resetPassword.changePassword': 'Passwort ändern',
    'resetPassword.fillAllFields': 'Bitte fülle alle Felder aus',
    'resetPassword.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein',
    'resetPassword.passwordMismatch': 'Passwörter stimmen nicht überein',
    'resetPassword.success': 'Passwort wurde erfolgreich geändert!',
    'resetPassword.error': 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
    // Login Checkout Screen
    'loginCheckout.title': 'Login',
    'loginCheckout.subtitle': 'Melde dich an',
    'loginCheckout.sectionTitle': 'Anmeldung',
    'loginCheckout.email': 'E-Mail / Benutzername',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Passwort',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Einloggen & Fortfahren',
    'loginCheckout.noAccount': 'Noch kein Account?',
    'loginCheckout.createAccount': 'Erstelle jetzt kostenlos einen Account',
    'loginCheckout.accountInfo': 'Mit einem Account kannst du deine Bestellhistorie einsehen und Treuepunkte sammeln.',
    'loginCheckout.fillAllFields': 'Bitte fülle alle Felder aus',
    'loginCheckout.invalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein',
    'loginCheckout.invalidCredentials': 'E-Mail oder Passwort falsch',
    'loginCheckout.total': 'Gesamt',
    // Order History Screen - erweitern
    'orderHistory.noOrders': 'Noch keine Bestellungen',
    'orderHistory.orderCount': '{count} Bestellung',
    'orderHistory.ordersCount': '{count} Bestellungen',
    'orderHistory.emptyTitle': 'Keine Bestellungen',
    'orderHistory.emptyDescription': 'Du hast noch keine Bestellungen aufgegeben',
    'orderHistory.orderNumber': 'Bestellung #{number}',
    'orderHistory.pickup': 'Abholung',
    'orderHistory.items': 'Artikel',
    'orderHistory.total': 'Gesamt',
    'orderHistory.statusPending': 'Ausstehend',
    'orderHistory.statusConfirmed': 'Bestätigt',
    'orderHistory.statusReady': 'Bereit',
    'orderHistory.statusCompleted': 'Abgeschlossen',
    'orderHistory.statusCancelled': 'Storniert',
    'orderHistory.loadError': 'Fehler beim Laden der Bestellungen',
    // Help & Support Screen
    'helpSupport.title': 'Hilfe & Support',
    'helpSupport.welcomeTitle': 'Wie können wir helfen?',
    'helpSupport.welcomeSubtitle': 'Hier findest du Antworten auf häufige Fragen und unsere Kontaktdaten',
    'helpSupport.faqTitle': 'Häufige Fragen',
    'helpSupport.contactTitle': 'Kontakt',
    'helpSupport.supportAvailable': 'Support verfügbar',
    'helpSupport.supportHours': 'Mo-Fr: 9:00 - 18:00 Uhr{newline}Sa-So: 10:00 - 16:00 Uhr',
    'helpSupport.urgentTitle': 'Dringende Probleme?',
    'helpSupport.urgentSubtitle': 'Bei dringenden Problemen mit deiner Bestellung rufe uns direkt an',
    'helpSupport.callNow': 'Jetzt anrufen',
    'helpSupport.faq1Question': 'Wie kann ich eine Bestellung aufgeben?',
    'helpSupport.faq1Answer': 'Wähle deine gewünschten Gerichte aus der Speisekarte aus, füge sie zum Warenkorb hinzu und gehe zur Kasse. Du kannst zwischen Abholung und Lieferung wählen.',
    'helpSupport.faq2Question': 'Welche Zahlungsmethoden werden akzeptiert?',
    'helpSupport.faq2Answer': 'Wir akzeptieren Kreditkarten, Debitkarten und Apple Pay. Alle Zahlungen werden sicher über Stripe verarbeitet.',
    'helpSupport.faq3Question': 'Wie kann ich eine Reservierung machen?',
    'helpSupport.faq3Answer': 'Gehe zum Home-Tab und wähle "Reservierung". Fülle das Formular aus und wir bestätigen deine Reservierung per E-Mail.',
    'helpSupport.faq4Question': 'Kann ich meine Bestellung stornieren?',
    'helpSupport.faq4Answer': 'Bestellungen können bis zu 15 Minuten nach der Aufgabe storniert werden. Kontaktiere uns direkt über die App oder telefonisch unter 0911 63290791.',
    'helpSupport.faq5Question': 'Wie lange dauert die Lieferung?',
    'helpSupport.faq5Answer': 'Die Lieferzeit beträgt normalerweise 30-45 Minuten, abhängig von der Entfernung und der aktuellen Auslastung.',
    'helpSupport.faq6Question': 'Was ist die Mindestbestellmenge?',
    'helpSupport.faq6Answer': 'Die Mindestbestellmenge beträgt 15€ für Lieferungen und 10€ für Abholungen.',
    'helpSupport.phone': 'Telefon',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'E-Mail',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Adresse',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlin',
    'helpSupport.hours': 'Öffnungszeiten',
    'helpSupport.hoursValue': 'Mo-So: 11:00 - 23:00 Uhr',
    // Imprint & Privacy Screens
    'imprint.title': 'Impressum',
    'privacy.title': 'Datenschutz',
    // Reservation Success Screen
    'reservationSuccess.title': 'Reservierung bestätigt!',
    'reservationSuccess.thankYou': 'Vielen Dank, {name}!',
    'reservationSuccess.reservationNumber': 'Reservierungsnummer',
    'reservationSuccess.confirmationSent': 'Eine Bestätigung wurde an {email} gesendet',
    'reservationSuccess.details': 'Reservierungsdetails',
    'reservationSuccess.date': 'Datum',
    'reservationSuccess.time': 'Uhrzeit',
    'reservationSuccess.guests': 'Anzahl Personen',
    'reservationSuccess.person': 'Person',
    'reservationSuccess.persons': 'Personen',
    'reservationSuccess.restaurant': 'Restaurant',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Nürnberg',
    'reservationSuccess.backToHome': 'Zurück zur Startseite',
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolgreich',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.required': 'Pflichtfeld',
  },
  en: {
    // Profile Edit Screen
    'profile.edit': 'Edit Profile',
    'profile.personalData': 'Personal Data',
    'profile.updateInfo': 'Update your account information',
    'profile.firstName': 'First Name',
    'profile.firstNamePlaceholder': 'Your first name',
    'profile.lastName': 'Last Name',
    'profile.lastNamePlaceholder': 'Your last name',
    'profile.email': 'Email Address',
    'profile.emailPlaceholder': 'your@email.com',
    'profile.language': 'Language',
    'profile.languageSubtitle': 'Choose your preferred language',
    'profile.save': 'Save Changes',
    'profile.saveSuccess': 'Profile updated successfully!',
    'profile.emailInfo': 'Your email address is used for order and reservation confirmations.',
    'profile.fillAllFields': 'Please fill in all fields',
    'profile.invalidEmail': 'Please enter a valid email address',
    'profile.error': 'Error',
    'profile.unexpectedError': 'An unexpected error occurred',
    // Language Options
    'language.german': 'Deutsch',
    'language.english': 'English',
    // Account Screen
    'account.title': 'Account',
    'account.subtitle': 'Manage your profile',
    'account.guest': 'Guest',
    'account.notLoggedIn': 'Not logged in',
    'account.loginNow': 'Login now',
    'account.loginSuccess': 'Successfully logged in!',
    'account.language': 'Language',
    'account.languageSubtitle': 'Choose your preferred language',
    'account.orders': 'My Orders',
    'account.ordersSubtitle': 'View order history',
    'account.editProfile': 'Edit Profile',
    'account.editProfileSubtitle': 'Name, Email, etc.',
    'account.logout': 'Logout',
    'account.logoutConfirm': 'Do you really want to logout?',
    'account.cancel': 'Cancel',
    'account.comingSoon': 'This feature will be available soon',
    // Home Screen
    'home.heroTitle': 'Two Worlds, One Vision - Asian Cuisine Reinterpreted',
    'home.heroSubtitle': 'Welcome to a world where tradition meets innovation',
    'home.chefQuan': 'Chef Quan',
    'home.chefQuanDescription': 'Quan combines the authentic flavors of his South Chinese homeland with modern creativity. Shaped by the vibrant markets of Guangzhou, he brings millennia-old culinary culture to small plates.',
    'home.chefRyohey': 'Chef Ryohey',
    'home.chefRyoheyDescription': 'Ryohey brings the high art of sushi craftsmanship to Nuremberg. With over 15 years of experience in the Edomae tradition, he creates each piece with respect for the product and Japanese perfection.',
    'home.reserveTable': 'Reserve Table',
    // Products Screen
    'products.title': 'Menu',
    'products.subtitle': 'Discover our delicacies',
    'products.highlights': 'Highlights',
    'products.smallDishes': 'Small Dishes',
    'products.fusionSpecials': 'Fusion Specials',
    'products.sushi': 'Sushi',
    'products.sides': 'Sides & More',
    // Cart Screen
    'cart.title': 'Cart',
    'cart.subtitle': 'Your selected items',
    'cart.items': 'items',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtext': 'Add products to get started',
    'cart.clear': 'Clear Cart',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    // More Screen
    'more.title': 'More',
    'more.subtitle': 'Additional Options',
    'more.contact': 'Contact',
    'more.contactSubtitle': 'Phone, Email & Address',
    'more.privacy': 'Privacy',
    'more.privacySubtitle': 'Privacy Policy',
    'more.imprint': 'Imprint',
    'more.imprintSubtitle': 'Legal Information',
    'more.appName': 'MOGGI App',
    'more.appSubtitle': 'Restaurant App',
    'more.appVersion': 'Version 1.0.0',
    'more.comingSoon': 'This feature will be available soon',
    'more.info': 'Info',
    // Navigation Tabs
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.more': 'More',
    // Contact Screen
    'contact.title': 'Contact',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.email': 'Email',
    'contact.openingHours': 'Opening Hours',
    'contact.copied': 'Copied',
    'contact.copiedMessage': '{label} has been copied to clipboard',
    'contact.copyError': 'Error',
    'contact.copyErrorMessage': 'Could not copy',
    // Login Screen
    'login.title': 'Login',
    'login.sectionTitle': 'Sign In',
    'login.emailLabel': 'Email / Username',
    'login.emailPlaceholder': 'max@example.com',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Forgot Password?',
    'login.button': 'Sign In',
    'login.fillAllFields': 'Please fill in all fields',
    'login.invalidCredentials': 'Email or password is incorrect',
    'login.emailNotConfirmed': 'Please confirm your email address',
    'login.error': 'An error occurred',
    'login.noAccount': 'No account yet?',
    'login.registerNow': 'Create a free account now',
    'login.accountInfo': 'With an account, you can view your order history and collect loyalty points.',
    // Register Screen
    'register.title': 'Register',
    'register.pageTitle': 'Create Account',
    'register.subtitle': 'Register for exclusive benefits',
    'register.firstName': 'First Name',
    'register.firstNamePlaceholder': 'Max',
    'register.lastName': 'Last Name',
    'register.lastNamePlaceholder': 'Smith',
    'register.email': 'Email',
    'register.emailPlaceholder': 'your@email.com',
    'register.birthDate': 'Date of Birth',
    'register.dayPlaceholder': 'DD',
    'register.monthPlaceholder': 'MM',
    'register.yearPlaceholder': 'YYYY',
    'register.password': 'Password',
    'register.passwordPlaceholder': '••••••••',
    'register.createAccount': 'Create Account',
    'register.fillAllFields': 'Please fill in all fields',
    'register.passwordTooShort': 'Password must be at least 6 characters',
    'register.invalidBirthDate': 'Please enter a complete date of birth',
    'register.emailAlreadyRegistered': 'This email is already registered. Please sign in.',
    'register.invalidEmail': 'Please enter a valid email address',
    'register.weakPassword': 'Password is too weak. Use at least 6 characters.',
    'register.error': 'An error occurred',
    'register.successTitle': 'Registration Successful!',
    'register.successMessage': 'Your account has been created.{newline}You will be redirected to sign in...',
    'register.terms': 'By registering, you accept our',
    'register.termsOfService': 'Terms of Service',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',
    // Checkout Screen
    'checkout.title': 'Checkout',
    'checkout.guestData': 'Guest Data',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.email': 'Email Address',
    'checkout.notes': 'Notes (optional)',
    'checkout.pickupDate': 'Pickup Date',
    'checkout.pickupTime': 'Pickup Time',
    'checkout.selectTime': 'Select Time',
    'checkout.selectTimePlaceholder': 'Select time',
    'checkout.selectDate': 'Select Date',
    'checkout.continuePayment': 'Continue to Payment',
    'checkout.fillAllFields': 'Please fill in all fields',
    'checkout.selectDateFirst': 'Please select a date first',
    'checkout.selectTimeFirst': 'Please select a time',
    'checkout.invalidEmail': 'Please enter a valid email address',
    'checkout.timeUnit': '',
    'checkout.pickupInfo': 'Your order will be prepared fresh. Please be on time for pickup at Katharinengasse 14, Nuremberg.',
    // Order Success Screen
    'orderSuccess.paymentSuccess': 'Payment Successful!',
    'orderSuccess.thankYou': 'Thank you, {name}!',
    'orderSuccess.orderNumber': 'Order Number',
    'orderSuccess.confirmationSent': 'A confirmation has been sent to {email}',
    'orderSuccess.pickup': 'Pickup',
    'orderSuccess.pickupDate': 'Pickup Date',
    'orderSuccess.pickupTime': 'Time',
    'orderSuccess.pickupAddress': 'Pickup Address',
    'orderSuccess.pickupAddressLine1': 'Katharinengasse 14',
    'orderSuccess.pickupAddressLine2': '90403 Nuremberg',
    'orderSuccess.newOrder': 'New Order',
    'orderSuccess.prepareToday': 'We are preparing your order fresh. See you soon!',
    'orderSuccess.prepareTomorrow': 'Your order will be prepared fresh tomorrow.',
    'orderSuccess.prepareLater': 'Your order will be prepared fresh on the pickup day.',
    // Payment Screen
    'payment.title': 'Payment',
    'payment.orderSummary': 'Order Summary',
    'payment.pickupDate': 'Pickup',
    'payment.amount': 'Total Amount',
    'payment.pay': 'Pay Now',
    'payment.error': 'Error',
    'payment.processing': 'Processing...',
    'payment.selectMethod': 'Choose your payment method',
    'payment.items': 'Items',
    'payment.time': 'Time',
    'payment.name': 'Name',
    'payment.securePayment': 'Secure Payment',
    'payment.creditCard': 'Credit Card via Stripe',
    'payment.sslEncrypted': 'SSL encrypted',
    'payment.pciCompliant': 'PCI compliant',
    'payment.allCards': 'All credit cards',
    'payment.stripeInfo': 'You will be redirected to the secure Stripe payment form. Your card data will be transmitted encrypted.',
    'payment.toPay': 'To pay',
    'payment.processingPayment': 'Processing payment...',
    // Reservation Screen
    'reservation.title': 'Reserve Table',
    'reservation.step1': 'Step 1: Date & Time',
    'reservation.step2': 'Step 2: Details',
    'reservation.selectDate': 'Select Date',
    'reservation.selectTime': 'Select Time',
    'reservation.time': 'Time',
    'reservation.guests': 'Number of Guests',
    'reservation.fullName': 'Full Name',
    'reservation.phone': 'Phone Number',
    'reservation.email': 'Email',
    'reservation.notes': 'Notes (optional)',
    'reservation.confirm': 'Confirm Reservation',
    'reservation.confirmed': 'Reservation Successful!',
    'reservation.confirmMessage': 'Your reservation has been confirmed. We look forward to your visit!',
    // Order History Screen
    'orderHistory.title': 'My Orders',
    'orderHistory.subtitle': 'Order History',
    'orderHistory.empty': 'No orders yet',
    'orderHistory.emptySubtext': 'Your orders will be displayed here',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.required': 'Required',
    // Dish Detail
    'dish.quantity': 'Quantity',
    'dish.addToCart': 'Add to Cart',
    // Verify Email Screen
    'verify.title': 'Verify Email',
    'verify.enterCode': 'Enter Code',
    'verify.codeSentTo': 'We sent a 6-digit code to',
    'verify.sent': '',
    'verify.warning': 'Important: Do not close this screen! If you leave, you will have to register again.',
    'verify.confirm': 'Confirm',
    'verify.resendCode': 'Resend Code',
    'verify.enterCodeError': 'Please enter the 6-digit code',
    'verify.invalidCode': 'Invalid Code',
    'verify.emailConfirmed': 'Email confirmed! Signing in...',
    'verify.loginFailed': 'Sign in failed. Please sign in manually.',
    'verify.newCodeSent': 'New code has been sent!',
    'verify.codeNotSent': 'Could not resend code',
    'verify.cancelTitle': 'Cancel Registration?',
    'verify.cancelMessage': 'If you cancel now, you will have to register again. The unverified account will be deleted.',
    'verify.stayHere': 'Stay Here',
    'verify.cancelButton': 'Cancel',
    // Forgot Password Screen
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.heading': 'Forgot Password?',
    'forgotPassword.subtitle': 'Enter your email address and we will send you a link to reset your password.',
    'forgotPassword.email': 'Email',
    'forgotPassword.emailPlaceholder': 'your@email.com',
    'forgotPassword.sendLink': 'Send Link',
    'forgotPassword.backToLogin': 'Back to Sign In',
    'forgotPassword.enterEmail': 'Please enter your email address',
    'forgotPassword.invalidEmail': 'Please enter a valid email address',
    'forgotPassword.emailSent': 'Email sent! Check your inbox and click on the link.',
    'forgotPassword.error': 'An error occurred. Please try again later.',
    // Reset Password Screen
    'resetPassword.title': 'New Password',
    'resetPassword.heading': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.newPasswordPlaceholder': 'At least 6 characters',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.confirmPasswordPlaceholder': 'Repeat password',
    'resetPassword.changePassword': 'Change Password',
    'resetPassword.fillAllFields': 'Please fill in all fields',
    'resetPassword.passwordTooShort': 'Password must be at least 6 characters',
    'resetPassword.passwordMismatch': 'Passwords do not match',
    'resetPassword.success': 'Password has been successfully changed!',
    'resetPassword.error': 'An error occurred. Please try again.',
    // Login Checkout Screen
    'loginCheckout.title': 'Login',
    'loginCheckout.subtitle': 'Sign in',
    'loginCheckout.sectionTitle': 'Sign In',
    'loginCheckout.email': 'Email / Username',
    'loginCheckout.emailPlaceholder': 'max@example.com',
    'loginCheckout.password': 'Password',
    'loginCheckout.passwordPlaceholder': '••••••••',
    'loginCheckout.loginButton': 'Sign In & Continue',
    'loginCheckout.noAccount': 'No account yet?',
    'loginCheckout.createAccount': 'Create a free account now',
    'loginCheckout.accountInfo': 'With an account, you can view your order history and collect loyalty points.',
    'loginCheckout.fillAllFields': 'Please fill in all fields',
    'loginCheckout.invalidEmail': 'Please enter a valid email address',
    'loginCheckout.invalidCredentials': 'Email or password incorrect',
    'loginCheckout.total': 'Total',
    // Order History Screen - expand
    'orderHistory.noOrders': 'No orders yet',
    'orderHistory.orderCount': '{count} order',
    'orderHistory.ordersCount': '{count} orders',
    'orderHistory.emptyTitle': 'No Orders',
    'orderHistory.emptyDescription': 'You have not placed any orders yet',
    'orderHistory.orderNumber': 'Order #{number}',
    'orderHistory.pickup': 'Pickup',
    'orderHistory.items': 'Items',
    'orderHistory.total': 'Total',
    'orderHistory.statusPending': 'Pending',
    'orderHistory.statusConfirmed': 'Confirmed',
    'orderHistory.statusReady': 'Ready',
    'orderHistory.statusCompleted': 'Completed',
    'orderHistory.statusCancelled': 'Cancelled',
    'orderHistory.loadError': 'Error loading orders',
    // Help & Support Screen
    'helpSupport.title': 'Help & Support',
    'helpSupport.welcomeTitle': 'How can we help?',
    'helpSupport.welcomeSubtitle': 'Here you will find answers to frequently asked questions and our contact information',
    'helpSupport.faqTitle': 'Frequently Asked Questions',
    'helpSupport.contactTitle': 'Contact',
    'helpSupport.supportAvailable': 'Support Available',
    'helpSupport.supportHours': 'Mon-Fri: 9:00 AM - 6:00 PM{newline}Sat-Sun: 10:00 AM - 4:00 PM',
    'helpSupport.urgentTitle': 'Urgent Issues?',
    'helpSupport.urgentSubtitle': 'For urgent problems with your order, call us directly',
    'helpSupport.callNow': 'Call Now',
    'helpSupport.faq1Question': 'How can I place an order?',
    'helpSupport.faq1Answer': 'Select your desired dishes from the menu, add them to your cart, and proceed to checkout. You can choose between pickup and delivery.',
    'helpSupport.faq2Question': 'Which payment methods are accepted?',
    'helpSupport.faq2Answer': 'We accept credit cards, debit cards, and Apple Pay. All payments are securely processed through Stripe.',
    'helpSupport.faq3Question': 'How can I make a reservation?',
    'helpSupport.faq3Answer': 'Go to the Home tab and select "Reservation". Fill out the form and we will confirm your reservation via email.',
    'helpSupport.faq4Question': 'Can I cancel my order?',
    'helpSupport.faq4Answer': 'Orders can be cancelled up to 15 minutes after placement. Contact us directly through the app or by phone at 0911 63290791.',
    'helpSupport.faq5Question': 'How long does delivery take?',
    'helpSupport.faq5Answer': 'Delivery time is typically 30-45 minutes, depending on distance and current volume.',
    'helpSupport.faq6Question': 'What is the minimum order amount?',
    'helpSupport.faq6Answer': 'The minimum order amount is €15 for deliveries and €10 for pickups.',
    'helpSupport.phone': 'Phone',
    'helpSupport.phoneNumber': '0911 63290791',
    'helpSupport.email': 'Email',
    'helpSupport.emailAddress': 'info@moggi-restaurant.de',
    'helpSupport.address': 'Address',
    'helpSupport.addressLine': 'Musterstraße 123, 12345 Berlin',
    'helpSupport.hours': 'Opening Hours',
    'helpSupport.hoursValue': 'Mon-Sun: 11:00 AM - 11:00 PM',
    // Imprint & Privacy Screens
    'imprint.title': 'Imprint',
    'privacy.title': 'Privacy',
    // Reservation Success Screen
    'reservationSuccess.title': 'Reservation Confirmed!',
    'reservationSuccess.thankYou': 'Thank you, {name}!',
    'reservationSuccess.reservationNumber': 'Reservation Number',
    'reservationSuccess.confirmationSent': 'A confirmation has been sent to {email}',
    'reservationSuccess.details': 'Reservation Details',
    'reservationSuccess.date': 'Date',
    'reservationSuccess.time': 'Time',
    'reservationSuccess.guests': 'Number of Guests',
    'reservationSuccess.person': 'person',
    'reservationSuccess.persons': 'persons',
    'reservationSuccess.restaurant': 'Restaurant',
    'reservationSuccess.restaurantAddress': 'Katharinengasse 14, Nuremberg',
    'reservationSuccess.backToHome': 'Back to Home',
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('de');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load saved language from AsyncStorage
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(STORAGE_KEY);
        if (savedLanguage && (savedLanguage === 'de' || savedLanguage === 'en')) {
          setLanguageState(savedLanguage as Language);
        }
      } catch (error) {
        console.error('Error loading language:', error);
      } finally {
        setLoading(false);
      }
    };

    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    
    // Ersetze Platzhalter wie {name}, {email}, etc.
    if (params) {
      Object.keys(params).forEach((param) => {
        text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
      });
    }
    
    // Ersetze {newline} mit \n
    text = text.replace(/\{newline\}/g, '\n');
    
    return text;
  };

  const getCategoryTitle = (categoryName: string): string => {
    return menuTranslations[language]?.categories[categoryName]?.title || categoryName;
  };

  const getCategorySubtitle = (categoryName: string): string => {
    return menuTranslations[language]?.categories[categoryName]?.subtitle || '';
  };

  const getDishDescription = (dishName: string): string => {
    return menuTranslations[language]?.dishes[dishName] || '';
  };

  const getTagTranslation = (tag: string): string => {
    return menuTranslations[language]?.tags[tag] || tag;
  };

  // Don't render children until language is loaded
  if (loading) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCategoryTitle, getCategorySubtitle, getDishDescription, getTagTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};
